### ISSUE TITLE
gscan_quic经常崩溃

### ISSUE THREAD

**Issue by jzmswe** [Kisesy/gscan_quic#101]
Ctrl+C不起作用，以前扫描线程700，昨天600还是崩溃，今天400试试。

表现特征为CMD窗口按哪个键都没反应，大概一个多月了，一直想反映这个问题，经常扫描了一夜早上一看，软件死了，一夜徒劳无功。

最新版4.1 GQ，OS win7 32 CHS。

**Comment by wenliyang** [comment]
// 注意:
// [扫描并发数] 理论上设置越大扫的越快, 但是并不意味越大就可以扫到更多IP
// 大量的并发数, 会造成网络堵塞, 甚至触到系统网络的限制或造成路由器宕机而出现更多的问题
// 所以如果在你那里基本扫不到IP, 可以试着减小扫描并发数并增大超时时间

配置文件说明里写得很清楚，一般请不要修改默认的扫描并发数，特别在墙不断加高的现在，减少这个数值可能更好些

**Comment by kirbyzhu** [comment]
是的 我一般设置60 100都容易出问题 欲速不达

**Comment by jasonliul** [comment]
ISP会限制并发数

通常控制在扫描4000左右IP, 完整字段15个上下.

**Comment by Kisesy** [comment]
这个没办法的，quic 本来就容易卡住，用 gop 也有时候卡住啊，别说这个工具是大线程扫了
所以设置好IP数量，扫完就结束，比较好

**Comment by Kisesy** [comment]
我加个 http 超时试试，一直想加的，老是忘记....

**Comment by Kisesy** [comment]
不过事实上，http 的超时是控制不了QUIC的。。。我把超时设置在 udp 上试试...

**Comment by Kisesy** [comment]
@jzmswe 要测试的话，重新下载最新的4.2，刚刚我更新了几次4.2

**Comment by jzmswe** [comment]
@Kisesy 多谢，我到今天22:00 PM再下载，临睡前扫描，早上来看结果。

**Comment by hcym** [comment]
一直能用，社长退隐后还没扫过
