### ISSUE TITLE
怎样设置才能使GQ在扫到自定义的IP数后，自动关闭CMD窗口

### ISSUE THREAD

**Issue by jzmswe** [Kisesy/gscan_quic#104]
我记得以前是能做到这一点的，现在搞成了按任意键才能关闭窗口。因为我这里最近经常早上停电，不想扫一夜后，停电导致一夜徒劳无功。

**Comment by Kisesy** [comment]
为什么觉得徒劳无功？暂停时不是已经显示文件都保存了吗，又不是按了键才保存
加暂停是因为很多人不会用 cmd 启动，导致出了问题，不知道哪里的问题，我也不想加，但是不得不加

**Comment by Kisesy** [comment]
我改了一下代码，程序扫描结束时，会正常退出，只会留下一个 cmd 窗口，这样没问题了吧
这样一来，你可以下个监视软件，监视这个进程，如果退出了就自动关机，还省电...

**Comment by Kisesy** [comment]
新版我也去掉了Windows以外系统的暂停，其他系统一般都是用命令行的吧...
