### ISSUE TITLE
4.3扫到自定义的IP数就死

### ISSUE THREAD

**Issue by jzmswe** [Kisesy/gscan_quic#106]
Ctrl+C不起作用，回车、ESC都没作用。自定义IP数100，超过100软件就死了，两次都是这样。自定义IP数2000，扫到一半，Ctrl+C倒是起作用。

**Comment by Kisesy** [comment]
把配置发一下

**Comment by jzmswe** [comment]
`	"ScanWorker": 600,
	"EnableBackup": false,
		// "InputFile": "./iprange_ping.txt",
	"QUIC": {
		"RecordLimit": 100,
	// "TLS": {
	// "SNI": {
`

**Comment by Kisesy** [comment]
我写在配置文件开头话你有没有看过？

**Comment by jzmswe** [comment]
4.4可以了，多谢，扫描并发数还是600。默认100太慢了，临睡前可100，早上起来看结果。

4.4还是最后按任意键退出窗口，能否搞成自动退出，我记得以前可以的。

**Comment by Kisesy** [comment]
你可能觉得我写的那段话没什么意思吧，如果是一般的tls扫描，你开多大的并发都没什么

但是这个不一样，比如说，扫描过程中按下 Ctrl+C，你看着是停止扫描了，也确实停止新建扫描了，但是之前已经启动的扫描是没有停止的，还是继续运行的，这些没停止，整个程序就不会结束，这个过程中如果有卡住的线程，那么整个程序都会卡住，这就是为什么Ctrl+C不好用的原因。线程越多，就越容易出现卡住，我不能解决这个卡住问题，我只能写那段话来让大家尽量避免这个

我已经加了选项了，你自己找

**Comment by jzmswe** [comment]
你加的选项找到了，非常感谢！
