### ISSUE TITLE
ReQrypt 作者新项目Tallow 牛油

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#108]
https://reqrypt.org/images/tallow_ui_on.png
ReQrypt 作者新项目Tallow 牛油, 这次是捅中国/伊朗墙来的~~~ LOL

Tallow
https://reqrypt.org/tallow.html
https://github.com/basil00/TorWall

Tallow - is a transparent Tor firewall and proxying solution for Windows. In a nutshell, when you run Tallow:

All traffic from your PC is transparently diverted through the Tor anonymity network. Programs do not need to be configured to use Tor.
All non-Tor related traffic such as UDP is blocked. This includes DNS-traffic to help mitigate leaks.

Tallow is not a complete strong anonymity solution, it's for anti censorship purpose.

Changelog
https://github.com/basil00/TorWall/releases

Tallow 1.0
https://reqrypt.org/download/TallowBundle-1.0-install.exe
https://reqrypt.org/download/TallowBundle-1.0-files.zip

**Comment by kirbyzhu** [comment]
连不上啊 26%的时候fail了
