### ISSUE TITLE
好像4.4版会在扫描到983000个IP的时候卡死

### ISSUE THREAD

**Issue by fei5seven** [Kisesy/gscan_quic#109]
扫到2000个左右实际扫过了983000个数目的时候按ctrl+C也没用了。心疼自己一波。没记错的话3.9好像不会

**Comment by caofengzi** [comment]
2000個還不夠用？

**Comment by fei5seven** [comment]
只是想测试一下呗，够用是够用了。3.9也会在983000强制停止=，=

**Comment by Kisesy** [comment]
以前没干扰，一般不会卡住，现在不行了
要是把代码改成2.0那样也许可以解决这个卡住问题，但是可能会出现内存泄漏和连接不释放问题，不过即使出现，也不如初代版本问题那么大，所以也算是个办法
开启 ping 也许也能解决，不过我不常扫IP，也不经常卡住，所以这两个方法我都不能保证...

**Comment by Kisesy** [comment]
又更新了一下，好像不卡了...

**Comment by fei5seven** [comment]
=，=现在的话100W以内差不多能扫个2000多一点，不然主任加一个980000自动停止先救急吧，不然卡住的话前面也白扫了

**Comment by Kisesy** [comment]
先试试 4.5

**Comment by fei5seven** [comment]
@Kisesy ok，试试去=，=

**Comment by caofengzi** [comment]
不要奢求那個時代了，能夠搜索出來可用的ip就行了，俺現在用的是17年10月份搜索的ip，那個時候就是開始屏蔽IPv4TLS協議的時候。

**Comment by fei5seven** [comment]
@caofengzi 是咯。从大大大大大大大大大大大大大大大大大大大开始，我以为会跟SS一样只是阶段性的，没想到是持续性的，我十月份扫到的现在全都炸了，只能扫新的来用，抛去断流不说，速度还是惊人=，=
