### ISSUE TITLE
sni ip无法使用？

### ISSUE THREAD

**Issue by NAVrasZ** [Kisesy/gscan_quic#115]
从以前的聊天记录扒了些ip，但扫出来的ip无法访问网页。
```
{
	"ScanMode":   "sni",

	"SNI": {
		"ServerName": ["www.apple.com", "www.microsoft.com"],
		"HTTPVerifyHosts": ["dns.google.com"],
		"Level": 3,
	},
}
```
level 2/3都试过，结果部分ip不同。
https://www.google.com
```The requested URL "[no URL]", is invalid.```
怀疑url被墙过滤，于是
https://www.reddit.com ; https://www.baidu.com 
```"error": "http: ContentLength=665 with Body length 0"```
level2 的结果在gp中显示全为goodip，无badip 但
```GAE *http.Transport.RoundTrip("https://www.googleapis.com/rpc") get HTTP Error 400```。
另外某个ip显示nginx的403。

p.s. 以前gp issue区的sni虽然也不能用，但看起来是普通```i/o timeout``` ```EOF```之类。

**Comment by SeaHOH** [comment]
servername 是否设置正确，需要设为未封锁的谷歌域名。

**Comment by NAVrasZ** [comment]
原来这样，改了gp后至少转到了google 404，先把gscan的servername也改了再扫一遍...
(话说gp和gscan的servername是什么？看讨论说是tls的sni，这样讲不通所以猜测为证书验证时用的域名，但现在这情况看起来不像

**Comment by SeaHOH** [comment]
扫的时候用一个以上未封锁域名，使用时至少一个未封锁的谷歌域名。

**Comment by NAVrasZ** [comment]
0个输出233...
```{
	"ScanMode":   "sni",

	"SNI": {
		"ServerName": ["connectivitycheck.gstatic.com"], //"fonts.googleapis.com", 
		"HTTPVerifyHosts": ["dns.google.com"],
		"Level": 2,
	},
}
```
测的J大和bamsoftware的列表

**Comment by hg123** [comment]
同样的IP前段时间用得好好的，今天突然不能用了，打开被墙网站出现以下提示

502 Bad Gateway

This HTTP request has a Host header that is not covered by the TLS certificate used. Due to an infrastructure change, this request cannot be processed.

可以使用google搜索 google其他服务都会出现以上提示。
请问下这是怎么回事？

**Comment by SeaHOH** [comment]
换一个域名

**Comment by SeaHOH** [comment]
任意有效 ID + `.appspot.com`

**Comment by hg123** [comment]
果然可用了，谢谢了

**Comment by hg123** [comment]
这墙看来是越高越厚了

**Comment by SeaHOH** [comment]
订正一下，似乎是谷歌自己改变了处理流程。

**Comment by hg123** [comment]
刚刚发现改成上面的域名后 无法使用google了 其他被墙网站却可以打开

**Comment by SeaHOH** [comment]
是的，因为 goproxy 不会更新了，我自己的 GotoX 做了处理能够正常使用。

**Comment by hg123** [comment]
下载了gotox 但不会用 
是不是得装python?

**Comment by SeaHOH** [comment]
是需要 Python 3。
可以到 releases 页面下载打包好的，不过这个还没更新，嫌手动更新麻烦的话，我可以发个新版。

**Comment by hg123** [comment]
我是下载了打包好的 也手动更新了 但我没找到exe运行程序啊 
不好意思 我是小白

**Comment by SeaHOH** [comment]
Windows 下双击 GotoX.vbs。

**Comment by hg123** [comment]
提示
行：7
字符：1
错误：系统打不到指定的文件
代码：80070002
源： (null)

**Comment by SeaHOH** [comment]
python 目录下有 python.exe 么？
下载打包的 windows 版本。

**Comment by SeaHOH** [comment]
奇怪，截个文件列表的图给我看看。

**Comment by hg123** [comment]
![tim 20180414153009](https://user-images.githubusercontent.com/736009/38765679-db051fb0-3ff8-11e8-8f95-8b561822df92.png)
![tim 20180414153034](https://user-images.githubusercontent.com/736009/38765682-e18a4d2e-3ff8-11e8-95c7-4dd1d1496049.png)

**Comment by hg123** [comment]
现在用其他的servername 打开google 也会出现502错误了 用appspot.com域名则是404错误

**Comment by SeaHOH** [comment]
看起来没啥问题，新建个快捷方式吧。
>也可以创建 GotoX\python\python.exe 的快捷方式来启动，
需要在属性->快捷方式->目标栏末尾添加“ ..\launcher\win32.py”。

**Comment by hg123** [comment]
好的我试试

**Comment by hg123** [comment]
有个窗口一闪就没了

**Comment by SeaHOH** [comment]
你是不是下载到 64 位的了？

**Comment by hg123** [comment]
没有啊 的的确确是32位

**Comment by SeaHOH** [comment]
哦，不好意思，我搞错了。
python 文件夹里面还有个 python 文件夹，把里面的所有文件剪切到第一个 python 文件夹。
等会儿我会修复发布版本。

**Comment by SeaHOH** [comment]
兼容 goproxy

**Comment by hg123** [comment]
看了下设置 不是很明白
 # 2018-4-14 更新：似乎只有 任意apppid.appspot.com 才能正常使用，已将填入的 appid 作为默认值
servername = 
这里填域名吧
sni的IP在哪填呢？是这里吗？
# GGC 或用于谷歌域名的反向代理
google_sni = 
#通用的反向代理列表请「一定」以 sni_ 作为前缀
#sni_xx =

**Comment by SeaHOH** [comment]
data 文件夹 ip.txt 文件，把里面全部换成 SNI IP。

**Comment by hg123** [comment]
终于用上了，谢谢

**Comment by SeaHOH** [comment]
默认配置是自动扫描，这个可以停止的，见 Config.ini 的 [gae/iplist] 注释。

**Comment by NAVrasZ** [comment]
同楼上
gotox的自动筛选用起来没问题

**Comment by Just2co** [comment]
@hg123 我昨天在goproxy里面使用SNI IP碰到的情况刚好跟你相反，我是谷歌相关的域名可以打开，跳到谷歌以外的域名全部都是403或者502错误，你是其他网站可打开，谷歌网站403 502错误，如果把我俩碰到的情况做一个合并，那么goproxy就可以像gotox一样 通过SNI 服务绕路连接GAE了。

**Comment by SeaHOH** [comment]
根据 servername 不同，SNIProxy 的连接结果就不同，需要做分别处理。

**Comment by Just2co** [comment]
@SeaHOH 这个变化应该是GAE升级规则之后才出现的吧？那得赶紧给谷歌那边发个邮件，不然以后再改来改去，通过SNI这个方式就用不成了！

**Comment by SeaHOH** [comment]
没必要，人家商业公司，有问题付费用户会报告。

**Comment by Just2co** [comment]
@SeaHOH "120.198.231.103","120.198.231.106","120.198.231.144","120.198.231.147"   这是我检测到的广州移动SNI IP，2016年用来绕路翻到GAE，现在放进去，网页自动跳转到cdn.com/_gw 这个页面报403错误

**Comment by SeaHOH** [comment]
IP 用途变化很正常，不用管它。

**Comment by Just2co** [comment]
@SeaHOH 我们现在搜到的SNI 都是国外的，我想找到国内电信或者移动的SNI，这样速度快一些，你觉得呢？如果把我上面提供的这些SNI用起来，那速度就给力多了！

**Comment by SeaHOH** [comment]
你提到的这几个 IP 已经不是 SNIProxy 了。

**Comment by Just2co** [comment]
@SeaHOH 我是用你给的那个网页检测 120.198.0.0/16 来获取的，并没有进行进一步测试，这个IP段也是2016年用过的广州移动的SNI IP所在的IP段

**Comment by SeaHOH** [comment]
我也没有仔细找过，就是之前选了 500+ 验证过的。
1. 设置自动筛选 50 个，一分钟左右搞定
1. 改为停止自动筛选，重启
1. 如果一段时间后连接失败率增加太多，或平均速度降低过多，重复以上步骤（实际上我几个月才重复了一次）

**Comment by Just2co** [comment]
@SeaHOH 上面这3个筛选步骤都是在gotox里面自动完成的吗？你开始是在gscan里面检测的SNI的吧

**Comment by SeaHOH** [comment]
对，是在讲 GotoX，不过最开始检测 SNI 是自己写的脚本，当时 gscan_quic 还没完善。

**Comment by Just2co** [comment]
我在gscan_quic 检测SNI的时候，最下面level必须设置为1才能检测出来IP，填2跟3一个都没有。检测域名用的是www.apple.com www.bing.com

**Comment by jasonliul** [comment]
得加hosts, 国内有投毒
13.107.21.200 www.bing.com
104.72.75.65 www.apple.com

**Comment by Just2co** [comment]
@jasonliul  回J大，hosts改了，把level改成2，还是一个IP都测不出来，只能改成1，就会出现一百多个IP，但是大部分都是不可用的，我放入gotox软件里面，自动检测出来了5个可用的，还是可以的，速度非常快，比QUIC跟teredo隧道快多了，也比较稳定。油管可以达到20Mbps，可以流畅4K了，非常不错！

**Comment by SeaHOH** [comment]
SNI 现在用的人比较少，所以速度还可以。

如果用户增加流量太多的话，速度会降下来，还可能连接不上，所以还有考虑增加其它方式。

还有一点就是，这些 SNIProxy 毕竟是别人的，以后可能会采取特殊的认证方式，如：来源 IP 范围。

**Comment by jasonliul** [comment]
SNI还是狗蛋方便, 非得用GP无意义
https://www.gogotunnel.com/home

**Comment by Just2co** [comment]
@SeaHOH 是的，我用的那几个IP好像都是欧洲那边的，延迟280ms以上的，之前用的国内广州20多毫秒，日韩30多毫秒的，现在一个都扫不到了！

**Comment by SeaHOH** [comment]
@jasonliul 狗蛋是很方便，支持多种方式，打分选择代理路径才是亮点。

**Comment by Just2co** [comment]
@jasonliul @SeaHOH  从哪里能搞到SNI代理测试用的IP段？是不是找到日韩IP段，放进去，大海捞针这样检测？

**Comment by SeaHOH** [comment]
之前我不是放了个维基的日志工具，里面可以看到哪些地址可能是 SNIProxy。
还有一些专门扫描服务端口的网页工具，之前社长也介绍过。

**Comment by jasonliul** [comment]
其实只有中美的sni多一些, 其他就是国内运营商在国外做的业务.

不过Haproxy的新版, 性质等同sni, 大概需要新的搜索测试工具.

**Comment by Just2co** [comment]
@SeaHOH 用钟馗之眼这种，类似之前搜索GVS主机一样，输入SNI直接搜索可不可以?

**Comment by SeaHOH** [comment]
@jasonliul 
Haproxy 和 SNIProxy 还是有区别的，前者一般作为负载均衡用于特定站点的前端，后者不会限制代理的网站，而且只支持 https 站点。应该不好区分出通用的 Haproxy，只有部署的人才知道。

@Just2co 没试过，你试试看？

**Comment by jasonliul** [comment]
@SeaHOH 
海少, 你的minixx能否升级quic-go?
https://github.com/lucas-clemente/quic-go/releases

今年谷歌升级之后, quic方式其实远比去年稳定, 例如越南那些113字头的渣ip, 现在quic也很可靠.

**Comment by NAVrasZ** [comment]
（之前试过把sni加到gogo中，报错和gp的一样

**Comment by SeaHOH** [comment]
@jasonliul 我写的是 GotoX 哇。
话说以前也想过加上 QUIC 协议，但是 Python 没有可用的库，用 Golang 我调试又不方便（其实主要是玩不来 :trollface: ）。
还有，TLS 1.3 不是要普及了么，看看效果。

**Comment by NAVrasZ** [comment]
之前把整个sni丢给gogo报错和gp一样，现在代理多了不太好测。
但刚才试了下把gotox的ip.use加进去仍是`www.google.com didn’t send any data.`

**Comment by SeaHOH** [comment]
@NAVrasZ 狗蛋中不是这样用的，你不能让被封域名直接走 SNI，只封 IP 的可以走。

**Comment by NAVrasZ** [comment]
原来如此~~

**Comment by MeABc** [comment]
TLS 1.3 应该可用了。上扫描工具。。。
话说主任这是要弃坑啊！ @Kisesy

**Comment by jasonliul** [comment]
@SeaHOH 
喔... 忘了这个.
今年的玩具明显偏少

**Comment by SeaHOH** [comment]
玩具其实不少，只是不好获取，在没有玩具的时候。

**Comment by hg123** [comment]
Google 的云计算平台 App Engine（GAE） 正在关闭域前置(Domain fronting)功能，导致利用 Google 域名绕过国家级审查的反审查工具失效。域前置是一种隐藏连接真实端点来规避审查的技术。此技术的原理为在不同通信层使用不同的域名。在明文的 DNS 请求和 TLS 服务器名称指示中使用无害的域名来初始化连接、公布给审查者，而实际要连接的被封锁域名仅在创建加密的 HTTPS 连接后发出，使其不以明文暴露给网络审查者。比如在没有屏蔽 Google 域名的国家，反审查工具可以通过 Google 的域名 appspot.com 转发流量。Tor 开发者在 4 月 13 日率先报告了 GAE 的域前置停止工作。域前置失效干扰到了 Signal、GreatFire.org 和 Psiphon VPN 等反审查服务。Google 的代表对此表示，域前置从来不是 Google 支持的一项特性，它能工作是因为软件栈的古怪行为，Google 在不断更新网络，作为计划中的软件更新的一部分，域前置不再能工作。Google 没有计划将其作为一项功能提供。
https://www.solidot.org/story?sid=56211

**Comment by Just2co** [comment]
@hg123 然而我们的 @SeaHOH 海少 已经率先研发成功，只需要判断需代理域名然后修改适合的servername递交代理请求，就可以成功get到需要的代理数据。谁能把goproxy也改一下，就也能使用SNI 穿墙了！

**Comment by hg123** [comment]
@Just2co 是啊 海少 第一时间就对gotox做了修改 赞一个
我也希望有高手能把goproxy改一下

**Comment by SeaHOH** [comment]
其实不用直连全部走 GAE 也能用 GoProxy，只是这样对谷歌认证有些影响。

**Comment by hg123** [comment]
刚才试了 将域名加到forcegae下 不会出现404错误了
但我不明白谷歌认证是指哪些认证 是指上传服务端时的认证吗？

**Comment by SeaHOH** [comment]
就是谷歌的帐号系统，上传会受到影响，U2B 也可能。

**Comment by Just2co** [comment]
@SeaHOH @jasonliul @Kisesy @MeABc  各位大佬，这是美国思科官方博客对TLS1.3协议新特性的一些介绍，着重强调了证书隐匿，SNI 加密，以及HTTPS透明代理及显式代理的处理  ：[https://blogs.cisco.com/security/the-impact-on-network-security-through-encrypted-protocols-tls-1-3](url)

**Comment by tec1987** [comment]
@Just2co TLS1.3何时能够普及。。。

**Comment by jasonliul** [comment]
@SeaHOH 
雕琢没有意义, quic是社长的遗产, 现在谷歌调整策略, DNS方式已经无用.

现在谷歌服务器每次增强对新协议quic的支持, 黄狗就复原几分.
其实很简单, 新IP段落? 是否能够更新quic-go核心模块?

社长退隐, 墙农没有借口再搞谷歌, 如果有vps普查谷歌新ip字段, 实际上黄狗就满血复活, 小众而已, 略懂略懂....

**Comment by MeABc** [comment]
"伯恩的遗产" 续集。。。。

![2018-04-23_154459](https://user-images.githubusercontent.com/18194126/39113370-01a1d386-470e-11e8-841d-231cb925866f.png)

看颜色。已和原来的不同。

**Comment by MeABc** [comment]
再也不用担心社长更改上游了。。。

https://github.com/MeABc/quic-go

**Comment by tec1987** [comment]
@MeABc 你这是啥？
自己更新了服务端？

**Comment by MeABc** [comment]
fork 了社长的编译链，自己编译的客户端，现在上游编译链可以更新到最新了，不依赖社长的，一键更新编译链到最新的。

**Comment by MeABc** [comment]
sync quic-go 稳定多了。效果明显。

**Comment by SeaHOH** [comment]
@jasonliul 肯定还会搞谷歌啦，哪个方便、流量大、容易针对就打击哪个。
QUIC 本地扫才好，VPS 上扫到的不一定能用。

@MeABc 这都多亏社长的努力啊，有没有放出来给大家用的想法？

**Comment by MeABc** [comment]
@SeaHOH 那是必须的啊！！！不过现在先放在 bitbucket 。等稳定了再放出。

**Comment by tec1987** [comment]
这是个好消息，感谢各位的付出
@MeABc

**Comment by jasonliul** [comment]
@MeABc 
很好, 终于有一个懂狗语的

**Comment by caofengzi** [comment]
@MeABc 希望早日放出穩定版，終於有一個人能夠維護gp了。

**Comment by no-name2017** [comment]
想请问下各位大佬，哪里还能下载到GoProxy？谢谢

**Comment by caofengzi** [comment]
@no-name2017等待@meabc 編輯的最新版本吧。

**Comment by MeABc** [comment]
`就会放出最新版的goproxy软件，针对QUIC进行了最新优化，并且修复谷歌GAE服务针对SNI做调整后代理部分失效问题，最新版满血复活，支持各类型前置代理，支持QUIC，支持IPV6，无敌了！`

@Just2co 大佬，你这广告打的让我有压力啊！！

我只是修复因上游的改变做一些适应性的修改，什么 `支持各类型前置代理，支持QUIC，支持IPV6` 这些本来就有的功能。。。

**Comment by MeABc** [comment]
说实话，即使我不更新，goproxy 也是一直可用的。只不用是上游一些如 go quic-go 等不能同步而已。

**Comment by caofengzi** [comment]
還是更新的好，性能肯定會有所提升的，俺現在用的ip還是全年搜索的呢。

**Comment by no-name2017** [comment]
谢谢各位大佬的努力

**Comment by jasonliul** [comment]
@MeABc 
白少不要紧张...
每次狗族散伙, 都有赠别ip, 俺找到几枚, 两枚神勇

早就甩开墙农, 绝尘遛狗去也~~

**Comment by pgz123** [comment]
期待期待

**Comment by fengixng** [comment]
期待，终于有人更新goproxy了

**Comment by noctwolf** [comment]
期待更新goproxy

**Comment by NAVrasZ** [comment]
:p

**Comment by blob2015** [comment]
@tec1987 @jasonliul @SeaHOH @Just2c @caofengzi @Kisesy yesterday once more
@MeABc abc兄彪悍，“伯恩的遗产”，这个厉害
