### ISSUE TITLE
促销 Windscribe VPN (50GB per Month)

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#120]
促销 Windscribe VPN (50GB per Month)
https://slickdeals.net/f/11503819-windscribe-vpn-50gb-per-month-free

注册
https://windscribe.com/

code: REDDIT50

Enter username, password, email and Voucher code
"Create Free Account"
Separately, you will get an email immediately, click the link in the email to confirm to apply the offer to your acount
If you already have an account, you may claim the voucher code by clicking "My Account" (top right side of page), "Claim Voucher" and then entering the voucher code
Your account dashboard should display the 50GB limit

**Comment by no-name2017** [comment]
多少钱一个月

**Comment by caofengzi** [comment]
主頁有介紹。

**Comment by no-name2017** [comment]
好的，谢谢大佬
