### ISSUE TITLE
墙民更难过, 大佬们撤出对反审查的支持

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#122]
谷歌, 亚马逊, Cloudflare...等巨型商家表明态度, 不再支持列国反审查墙民, 下架自家domain fronting, 网络人权组织Digital rights groups 只能哀嚎~~

域名欺诈相关的反审查软件, 将不再可用, 例如洋葱的meek.

https://www.theverge.com/2018/4/18/17253784/google-domain-fronting-discontinued-signal-tor-vpn
https://www.techrepublic.com/article/as-google-and-aws-kill-domain-fronting-users-must-find-a-new-way-to-fight-censorship/
https://bsodsoftware.com/2018/05/amazon-closes-anti-censorship-loophole-on-its-servers/

**Comment by tec1987** [comment]
“域前置”（Domain Fronting，也被意译为“域名幌子”）技术是把双刃剑，禁用主要是出于网络安全考虑

**Comment by SeaHOH** [comment]
域内仍然支持，只是不能跨域。

**Comment by wegood9** [comment]
可惜了meek网桥

**Comment by qwertccc** [comment]
meek很早以前就不能使了。。。。。

**Comment by qwertccc** [comment]
现在tor完全不能使了，必须得来个前置，但是这玩意儿本身就慢，你再套个前置。。。。还用个毛线

**Comment by Just2co** [comment]
可以找速度快的前置啊，program-think一直都是用的前置加tor，他写博客需要查到大量的素材，那速度不是得慢死？

**Comment by jasonliul** [comment]
ChrisPC Free Anonymous Proxy 这个加前置, 直接使用网桥, 也有6,7M带宽
