### ISSUE TITLE
https 节点by puff1984 

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#123]
puff1984 大大提供
【测试】 HTTPS PROXY 服务器 http://maomi.us 端口 443

Chromium 类浏览器可以直接设置, 其他需要stunnel,
https://www.stunnel.org/downloads.html

教程自搜~

**Comment by kirbyzhu** [comment]
stunnel没有一个很友好的手机客户端。

**Comment by jasonliul** [comment]
stunnel 其实有一个旁支版本
https://github.com/kaleb-himes/stunnel

使用WolfSSL, 指纹少得可怜

**Comment by tec1987** [comment]
感谢分享，留着备用
