### ISSUE TITLE
全球墙民世界地图

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#124]
全球墙民世界地图
http://i64.tinypic.com/vpi5wj.jpg

网民自由比例
https://freedomhouse.org/sites/default/files/FOTN2017_Web_Chart_800px_Percentage-Of-Global-Users-By-Rating-Donut-Chart.png

因特网用户分布/自由状态
https://freedomhouse.org/sites/default/files/FOTN2017_Web_Chart_800px_Distribution-of-Global-Users-Cartogram-Map.png

**Comment by tec1987** [comment]
第一个打开看不到图。。
后面域名有DNS污染。。。

**Comment by 973204** [comment]
这图应该是AM出的，他的小弟都很自由的！
