### ISSUE TITLE
常见番茄工具, 还有活着的吗? 大家来哈拉~~

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#127]
UltraSurf 生猛
俄友美化版 https://www.datafilehost.com/d/494a15e2

**Comment by Kisesy** [comment]
J哥忘了解压密码：ru-board

**Comment by tec1987** [comment]
。。。还活着，快被热死了

**Comment by jasonliul** [comment]
@Kisesy 
呜~~

**Comment by panpeach** [comment]
一直活的很好，低谷时段1080p不成问题^_^。

**Comment by pgz123** [comment]
abc的伯恩呢？好期待

**Comment by MeABc** [comment]
![image](https://user-images.githubusercontent.com/18194126/41100501-1f0f55b6-6a94-11e8-8e24-a8aba6fd1f97.png)

代码上应该是没有太大问题了，放在 sniproxy 里可以过，但是手上没有好 ip ，没法验证直连下的情况。
目前正在想办法完善我的扫描工具。。。。

**Comment by MeABc** [comment]
开句玩笑话：现在不是在写代码的路上，而是在找 IP 的路上。。。。

**Comment by SeaHOH** [comment]
用 IPv6 就行，如果你要扫 IPv4，我可以把工具发出来。
但是功能很简陋，因为没想到还会有啥大用处。

**Comment by jasonliul** [comment]
@MeABc 
先发再说...狗不遛肿么知道是活的?

**Comment by MeABc** [comment]
@jasonliul 好的，这个尽快。。。

@SeaHOH 谢谢！这个先不用。

**Comment by jasonliul** [comment]
@MeABc 
夏天到了, 白少终于进化为蚊子出来咬墙了~~

来段音乐, 为白少壮游助兴:
https://youtu.be/HETRaN9tjXE?list=LLQ4xGnSfjNiFJ4NfH1cDySA

**Comment by MeABc** [comment]
话说要是把新的 repo 取名为 ERA 这种霸气的名字会不会死得更快。。。

**Comment by jasonliul** [comment]
@MeABc 
不如Divano?

Era另一首Ameno也是经典
https://youtu.be/ai7sTP6-jrw?list=LLQ4xGnSfjNiFJ4NfH1cDySA

**Comment by jasonliul** [comment]
《The Mass》中英雙語歌詞：

【O Fortuna 哦，命運】

【velut luna 就像月亮】

【statu variabilis 總是變化】

Semper crescis 始終滿盈

Aut decrescis 或又虛虧

Vita detestabilis 可惡的生活

Nunc obdurat 時而鐵石心腸

Et tunc curat 時而又關心撫慰

Ludo mentis aciem 當作遊戲一般

Nunc obdurat 時而鐵石心腸

Et tunc curat 時而又關心撫慰

Ludo mentis aciem 當作遊戲一般

Egestatem 窮困

Potestatem 權力

Dissolvit ut glaciem 被它如冰雪般融化

Divano 聖哉

Divano me 聖哉，彌

Divano messi 聖哉，彌賽

Divano messia 聖哉，彌賽亞(救世主)

Divano messia 聖哉，彌賽亞

Divano

Divano me

Divano messia

Divano messia

【原文這裡還有一段，Era的版本出於某種原因去掉了】

Sors salutis 命運將我的健康

Et virtutis 與道德情操

Michi nunc contraria 時時摧殘

Est affectus 虛耗殆盡

Et defectus 疲勞不堪

Semper in angaria 永遠疲於奔命

Hac in hora 就在此刻

**Comment by jasonliul** [comment]
@MeABc 
https://gitter.im/MeABc
俺发给你了, 在役ip

**Comment by MeABc** [comment]
@jasonliul 哇，非常感谢 J 哥！！！

**Comment by tec1987** [comment]
好久没来，居然不知道你们在聊啥。。。

**Comment by SeaHOH** [comment]
@MeABc 进不去，拉我~

**Comment by SeaHOH** [comment]
不是 https://gitter.im/MeABc 吗，社长那里没看到。

**Comment by SeaHOH** [comment]
>我发现我属于重灾区，还是安安心心的扫 IP 吧。。。

其实 IPv6 挺好用

**Comment by MeABc** [comment]
J 哥给我的私信，我们私聊的。

**Comment by SeaHOH** [comment]
了解

**Comment by MeABc** [comment]
我先发源码吧。 
https://github.com/MeABc/zebra 

懂的可以自己先编译。这几天抽时间搞那个 CI 。

![image](https://user-images.githubusercontent.com/18194126/41148225-0a02eee2-6b3b-11e8-92c9-0928263777ed.png)

**Comment by jasonliul** [comment]
@MeABc 
重灾区?
列位拿ip砸白少罢~~~

**Comment by MeABc** [comment]
@jasonliul 谢谢！不过大家不用给我发，发过来也没有用，环境不一样，用不了的。可以叫小白，这样可以显得我很年轻。。。

**Comment by MeABc** [comment]
扫了40W个，得6个。啊啊啊。。。。真是惨。。。
通过打开我常用网址测试，暂时没有发现什么问题。

**Comment by jasonliul** [comment]
@MeABc 
看来你是学贼网~~~ :)

**Comment by pgz123** [comment]
我等才是小白呀。看不懂.

**Comment by SeaHOH** [comment]
@MeABc 
QUIC 吗？这么惨。。。
不打算用 IPv6 吗？

**Comment by MeABc** [comment]
@SeaHOH tls v4 。

平时用 quic ，留着这几个 IP 当种子用来测试。
因有些软件不支持 v6 ，所以暂时不搞这个。

**Comment by SeaHOH** [comment]
可以用 SNIProxy 来测试 TLS IPv4，基本没有差别。
不过话说回来，也指望不上 gws 和 ggc 了，可用数量太少。

**Comment by pgz123** [comment]
MeABc 的新狗还没放飞吗？好久没遛狗了

**Comment by qwertccc** [comment]
v4的quic，延迟放到2s，我还可以有3k多可用，800ms的话就100来个

我现在就这100来个，扛了几个月了，舒爽

**Comment by jasonliul** [comment]
@qwertccc 
当下还有几个?

**Comment by blob2015** [comment]
@qwertccc @jasonliul 
估计也差不多歇菜了……
看来搞不好，得试试新玩具了
