### ISSUE TITLE
忽然好怀念社长....

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#128]
含饴弄孙去鸟....

来来来, 狗友们每人汪汪两声, 赠与社长殿~~ :)

**Comment by tec1987** [comment]
汪汪、旺旺。。。

**Comment by wegood9** [comment]
有社长的日子比现在好过多了

2018-05-31 0:47 GMT+08:00 tec1987 <notifications@github.com>:

**Comment by 973204** [comment]
除了汪两声，没其他加成 @ @

**Comment by NAVrasZ** [comment]
🐶

**Comment by Asteroids89** [comment]
🐶🐶

**Comment by qwertccc** [comment]
=.=

**Comment by qwertccc** [comment]
@phuslu 

能at到吗，过来聊天扯淡啊

**Comment by SeaHOH** [comment]
能看到，但是不能来聊了，这道理应该懂才是。

**Comment by pgz123** [comment]
社长好.我们没有忘记你

**Comment by jasonliul** [comment]
作为华人不至于堕落成人皮牲口的支柱...
中国从来不欠缺发哥社长, 大众脊梁, 圣贤门下. 吾等草贱所以依托不至于人性沦丧.

惭愧吾等成为中国无骨草贱, 值此6.4国士日, 秉诚致意社长等中国人 - 当之无愧的中国人. 炎黄子孙, 汉唐余烈.
