### ISSUE TITLE
真话难听.... 关于V2Ray

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#131]
http://lancelv.blogspot.com/2017/07/v2ray.html

俺邀请过国外软件测试群, 比对V2ray与其他代理, 包括SS, 结果也是如此.

remark":"Kr","address":"13.112.163.247","port":8080,"users":[{"id":"f5569f64-4479-4a2e-8665-517f687e9a7e","alterId":32,
匿名大大提供的KR节点

**Comment by panpeach** [comment]
速度不错，非常感谢。
