### ISSUE TITLE
Outline 剪影, 纸飞机变种, 谷歌做幕后黑手

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#133]
洋人也玩剪影, 中国墙人人可操
https://www.reddit.com/r/outlinevpn/

洋评测
http://startuplivingchina.com/how-to-outline-vpn-setup-china/

台湾几位高中小朋友推介Outline
https://blog.allenchou.cc/google-outline/

Google周二也發表了來自Jigsaw的開源工具Outline，以供新聞組織於自家伺服器上設定VPN，以保障新聞從業人員的網路存取安全，且標榜不需技術人員就能完成設定。
https://www.ithome.com.tw/news/121965
呆湾友新闻

**Comment by blob2015** [comment]
J哥好，不会因为这个，gp被咯p了吧？
今天这边，gp第一次不能用了。

**Comment by jasonliul** [comment]
确实可用ip锐减.
不过应该是针对XX-net, 俺这里还有ip, 去XX组侦查一下再说罢~~

**Comment by blob2015** [comment]
那也是大有可能，毕竟ipv6铺开了在xx手上，最近，这边搞了个行动，上海那边领头的，那个就不知道有没有关系了

**Comment by jasonliul** [comment]
"223.25.255.229", "180.210.155.228", "103.229.45.197", "163.47.157.132", "103.197.248.228", "103.68.116.133", "163.47.157.133", "103.230.4.198", "103.68.116.132", "103.15.246.101", "103.230.4.196", "180.211.173.229", "103.54.38.197", "180.211.173.228", "103.197.248.229", "103.54.38.196", "27.147.199.4", "220.158.234.4", "59.152.108.165", "59.152.108.164", "58.145.190.6", "58.145.190.4", "58.145.190.7", "103.229.45.196", "27.147.198.4", "58.145.190.5", "27.147.198.5", "180.210.155.229",

放一些救急,.. 不是很出色那些

**Comment by jasonliul** [comment]
49.207.47.133|49.207.47.132|42.106.128.11|42.106.128.68|42.106.128.4|103.28.156.5|42.106.128.9|42.106.128.7|49.44.142.230|42.106.128.37|42.106.128.200|49.44.143.6|49.44.184.6|42.106.128.201|49.44.143.9|42.106.128.197|103.49.116.4|42.106.128.5|42.106.128.202|42.106.128.8|42.106.128.203|49.44.143.43|42.106.128.196|49.44.143.7|49.44.184.137|42.106.128.228|49.44.184.139|49.44.184.69|49.44.142.199|42.106.128.6|103.28.156.4|42.106.128.38|42.106.128.100|42.106.128.107|42.106.128.198|49.44.143.8|49.44.140.9|42.106.128.72|49.44.140.43|49.44.142.6|49.44.143.11|42.106.128.71|42.106.128.69|49.44.184.68|49.44.142.107|42.106.128.104|42.106.128.106|42.106.128.199|42.106.128.103|42.106.128.101|49.44.143.41|49.44.184.10|49.44.143.5|49.44.142.201|49.44.140.74|49.44.140.11|49.44.184.136|49.44.143.10|49.44.142.38|49.44.184.133|103.49.116.5|49.44.139.198|103.94.136.228|103.94.136.229|103.193.89.4|223.224.17.4|223.196.150.4|223.224.17.5|202.88.187.132|117.219.236.68|117.219.236.69|223.196.144.4|117.219.234.69|223.196.144.7|223.196.144.5|117.219.238.5|117.219.234.68|117.219.236.4|202.88.187.133|117.219.236.132|117.219.236.5

**Comment by blob2015** [comment]
感谢J哥，好久没有折腾了，看来得稍微折腾下了。
@MeABc ABC兄，你的update还发不？
@phuslu 小怀念下社长，能勃起这么久，也是难得了 :grinning:

**Comment by jasonliul** [comment]
@phuslu
社长威武~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by caofengzi** [comment]
俺這裡從昨天晚上開始quic協議ip4已經很少很少了，重新掃描基本上沒有了。聯通

**Comment by jasonliul** [comment]
这几天封杀的纸雕也相当可观....

破墙就像卫生棉, 用几天就会侧漏, 一如既往~

**Comment by pgz123** [comment]
@MeABc ABC兄，你的更新还发不？同问

**Comment by NAVrasZ** [comment]
自测outline在国内用不是很快，不如自己部署的libev

**Comment by jasonliul** [comment]
VPS部署Streisand --M cl 大大
https://github.com/mixool/mixool.github.io/wiki/VPS%E9%83%A8%E7%BD%B2Streisand

这个才最方便, 顺带多几种方式~~

**Comment by MeABc** [comment]
@blob2015 @pgz123 
呃，前段时间电脑坏了。。。。
会更新的。

有一个 bug 正在解决，另打让 Quic 支持前置。

**Comment by blob2015** [comment]
@MeABc 这是最近听到的最好的消息 :grinning: 
也尽量低调，人红是非多，但也不必过于惊恐，保重 :beers: 
ABC兄的斑马，目前还是很很低调的 :100:

**Comment by SeaHOH** [comment]
也不差那么一会，反正源码都放出来了。
等正式版本发出来，大家都会来捧你的场。 :smile:
