### ISSUE TITLE
6/21 免费美洲大带宽袜4

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#135]
107.173.16.148:8080
108.60.101.2:52660
131.0.62.1:33325
136.24.133.49:33325
138.0.204.122:31386
138.0.205.81:31386
138.97.236.13:1080
143.137.153.27:31231
149.36.44.197:8841
162.223.88.232:2020
162.223.88.235:8181
168.228.152.109:1080
168.228.152.14:1080
168.228.154.1:1080
170.238.119.77:1080
177.11.136.134:1080
177.126.81.63:32142
177.222.253.206:1080
177.39.211.91:1080
179.127.175.210:1080
181.112.61.162:1080
181.113.121.158:33555
181.143.232.58:80
181.211.166.105:31231
186.117.156.147:1080
186.121.206.234:1080
186.121.206.239:1080
186.121.206.240:1080
186.201.183.179:1080
186.225.119.101:1818
186.225.241.20:1080
186.225.98.234:41599
186.226.174.47:8080
186.235.35.121:32142
186.46.94.18:1080
186.96.103.230:1080
186.96.116.42:31546
187.243.251.34:1080
187.94.99.194:1080
189.20.32.90:1080
189.52.165.134:1080
190.108.35.126:1080
190.108.35.128:1080
190.108.35.131:1080
190.108.35.133:1080
190.108.35.144:1080
190.108.35.146:1080
190.108.35.147:1080
190.108.35.151:1080
190.108.35.158:1080
190.108.35.159:1080
190.108.35.168:1080
190.108.35.169:1080
190.108.35.16:1080
190.108.35.170:1080
190.108.35.180:1080
190.108.35.182:1080
190.108.35.188:1080
190.108.35.195:1080
190.108.35.197:1080
190.108.35.205:1080
190.108.35.211:1080
190.108.35.218:1080
190.108.35.227:1080
190.108.35.245:1080
190.108.35.249:1080
190.108.35.250:1080
190.108.35.29:1080
190.108.35.47:1080
190.108.35.4:1080
190.108.35.56:1080
190.108.35.6:1080
190.12.8.146:1080
191.243.53.129:41599
191.243.54.245:41599
191.37.28.18:1080
191.53.112.170:35618
200.107.253.132:1080
200.107.253.136:1080
200.107.253.138:1080
200.107.253.193:1080
200.13.160.125:31231
201.184.81.78:1080
204.145.81.52:1080
206.71.228.129:8841
206.71.228.193:8841
216.176.131.242:8841
216.176.132.19:8841
216.176.132.20:8841
216.54.3.241:8841
216.54.3.248:17641
216.54.3.250:17641
216.54.3.252:27723
216.54.5.38:8841
24.227.184.162:1080
38.103.238.33:54046
38.103.238.41:54046
38.103.239.13:54046
38.103.239.2:40656
38.103.239.5:40656
38.103.239.6:54046
38.103.239.9:54046
38.96.151.167:8841
45.6.101.30:1080
66.70.160.171:1080
69.46.242.225:8841
69.46.242.2:8841
69.46.242.9:8841
69.46.243.129:8841
69.46.243.17:8841
69.46.243.25:8841
69.46.243.89:8841
69.46.243.9:8841
69.46.250.153:8841
69.46.250.177:8841
74.114.232.121:15706
74.114.235.139:46756
74.114.236.102:46577
75.151.213.85:3366
76.72.254.222:1080
8.46.64.38:1080
8.46.64.42:1080

实际上袜5并非真正免费, 绝大多数是免费Demo,
袜4基本都是公益目的, 带宽稳定存活期长, 其中的经典节点已经超过10年历史.

使用袜4/5
https://plus.google.com/+LiuJason999/posts/BYsVS3zpawm

**Comment by blob2015** [comment]
感谢J哥

**Comment by blob2015** [comment]
@SeaHOH 
大海兄，quic与tls是啥关系？即支持quic的，一定支持tls？还是？
因为要挂前置，对这个还是懵懂得很，之前遗留的大ip库，好像不怎么好，如果加袜子前置的话。

**Comment by jasonliul** [comment]
@blob2015
quic模式不支持前置, 如果你保留了旧模式的配置文件...
加上前置, 跟从前基本一样飞快

**Comment by jasonliul** [comment]
@blob2015 
https://www.ssrshare.com/forums/ssr-socks-v2ray.2/

玩雕再说~

**Comment by SeaHOH** [comment]
支不支持主要看谷歌态度，至于后面的 502 提示就是域前置失效的提示。
杰哥这个分享很棒啊，都是外国墙民的干货。

**Comment by blob2015** [comment]
@SeaHOH 呃，就是用主任的工具扫一遍就能剔除了？域前置失效，倒是听说过，原来就是指的这个啊。

**Comment by blob2015** [comment]
@jasonliul J哥，整理你在G+的帖子，发现你发的gp是1651版本，但是印象当中，社长的最后版本是1624吧？ABC兄收藏的，也是这个版本。这个是啥故事来着？

**Comment by jasonliul** [comment]
@SeaHOH 
前3年, 每天i都有几百枚高带宽美洲免费袜5, 墨西哥, 巴西, 赞助方是一家加拿大人权组织, 但去年年底, 他们发了一篇研究文字, 表示这种廉价前置对全球墙民帮助多多, 云云....

然后不再赞助.

因此受益, 而且成风的有巴西, 伊朗, 也门, 越南....不少的墙民, 唯独没有中国.
中国墙民也是玩遗产.国货的过气物种 LOL

**Comment by SeaHOH** [comment]
主要是我国墙民这个数量有点可怕，其实一直有人在做免费公开的，但是好多都被吓着了吧。
而且付费的广告无孔不入，免费的都不会传播的太广。

我还是一直专注如何扒稳谷歌的腿毛不要被甩掉~

**Comment by jasonliul** [comment]
@SeaHOH 
俺也不时摸摸ip, 习惯了~~ :)

**Comment by blob2015** [comment]
@SeaHOH 最开始，俺是买vpn的，但那个问题不少，而且不说每个月吧，至少每年总有那么几天，说关就关。更加重要的，基本上就是这么一个轮回：还行，然后宣传出名，然后用户大量上升，然后被XX盯上，然后人去楼空。你说的“数量”问题，某种角度看，确实是问题。
再问下，这种域前置问题，能通过ip筛选来解决不？现在就是想着用前置，但这个遗留的老库，必须得筛选才行，我看大海兄在xx那边说，v4的，很容易死，不知加挂之后也这样？
@jasonliul J哥，你的救急ip，感觉像是摸鱼摸的吧 :grinning:

**Comment by SeaHOH** [comment]
不想麻烦就用 IPv6 吧，用 hosts 效果很好。

**Comment by jasonliul** [comment]
@blob2015 
因为南亚ip从来没有人用....
:)

**Comment by blob2015** [comment]
@jasonliul 如果让阿三看到了J哥这话，阿三肯定又是一顿mmp :grinning:

**Comment by Just2co** [comment]
@jasonliul 南亚IP之所以没有人用，是因为没有直达中国大陆的海缆，都是从美国或者日本那边绕路的，而且居民宽带都是不对等的，上传速度很慢，大型商业公司又很少有开源共享精神。

**Comment by blob2015** [comment]
公司、中大型公司，大多想着搞一条自己的专线来着，为着安全考虑，或者其他考虑。

**Comment by blob2015** [comment]
@Just2co 刚才查了一下，好像是有直连光缆的：
> 亚欧5号（SMW5）、亚太直达（APG）海底光缆已于近期正式开通并投入使用。
> 两条海缆在新加坡中立POP点（网络服务提供点）互联后，打通了中国大陆、日本、韩国等亚洲国家至非洲、欧洲方向的大带宽通道，带宽达到100Gbps（12.5GB/s）
> 亚欧5号海缆，连接新加坡、马来西亚、印度尼西亚、孟加拉国、斯里兰卡、缅甸、巴基斯坦、吉布提、沙特、阿联酋、埃及、土耳其、意大利、法国等19个国家，骨干段设计容量为24Tbps，直接延伸至法国、意大利、新加坡中立POP点。
> 亚欧5号、亚太直达海缆还会接入即将开通的亚非欧一号(AAE-1)海缆，实现亚非欧方向双路由，互为保护
> 亚欧非一号海缆将和亚欧5号海缆共同连接新加坡、马来西亚、缅甸、印度、巴基斯坦、卡塔尔、阿联酋、阿曼、也门、吉布提、沙特、埃及、法国、意大利等14个国家，同时接入印度尼西亚、斯里兰卡、孟加拉、土耳其。

**Comment by Just2co** [comment]
虽然有直连海缆，但是你的数据包仍然也是绕路的，不是直连的，故意路由成绕来绕去，你可以路由追踪下你的数据包，这是出于何种目的呢？

**Comment by jzp820927** [comment]
@blob2015 想不到，居然还有人记得我，自从 gop 消失以后，确实很久没来 github 上面了，现在用 vps，所以也懒得折腾了，不过今天没事，跑来看看，想不到还有人问起我。

**Comment by blob2015** [comment]
@jzp820927 :grinning: 有啥vps推荐没？

**Comment by jzp820927** [comment]
这里面这么多高手，经常有人推荐，不用我推荐了吧
