### ISSUE TITLE
6/23 亚洲免费袜子

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#137]
103.75.190.230:1080
103.115.42.147:1080
103.214.167.100:1080
110.232.67.222:11574
110.232.77.98:19098
118.184.4.30:1080
122.10.86.216:1080
139.59.101.223:1080
139.59.109.156:1080
139.59.53.105:1080
139.59.53.106:1080
139.59.57.186:1080
139.59.59.63:1080
139.59.61.229:1080
139.59.61.29:1080
139.59.62.255:1080
139.59.99.101:1080
139.59.99.113:1080
139.59.99.119:1080
139.59.99.234:1080
139.59.99.63:1080
139.59.99.97:1080
163.47.11.113:1080
188.166.216.210:1080
202.63.48.72:64119
218.150.78.235:8080
218.150.78.251:8080
220.225.85.82:1080
42.112.208.124:64012
61.41.9.213:1081
61.41.9.213:10081
89.219.32.83:34040

袜4
114.33.75.32:1080
118.184.4.30:1080
118.193.175.253:1080
118.194.132.52:27202
124.244.21.131:1080
202.166.196.6:31546
182.93.88.194:1080
202.179.4.74:1080
223.242.93.27:41443
92.47.30.74:35618

Sstap 教程
https://www.ssrshare.com/threads/socks5-2018-02-12.134/

使用袜4/5
https://plus.google.com/+LiuJason999/posts/BYsVS3zpawm

SocksCap64 使用教程
https://www.ssrshare.com/threads/sockscap64.74/

proxifier使用教程
https://www.ssrshare.com/threads/proxifier.258/

**Comment by blob2015** [comment]
感谢J哥，感谢那位教程兄

**Comment by jasonliul** [comment]
@blob2015 
Quic模式不支持前置

**Comment by blob2015** [comment]
@jasonliul 就是俺添加的那些个ip，刚好抽取到的ip不支持tls模式？谢谢J哥指点，我试试老GA里面的ip

**Comment by ruby186** [comment]
quic是彻底不能用了，还是？J哥@jasonliul

**Comment by blob2015** [comment]
@ruby186 能用，但好像需要修补一些东西。XX更新了证书，其重点是ipv6，但没有迈入quic。多备几个，比如ss等等。

**Comment by MeABc** [comment]
tls 和 quic 都可以用。问题在于 IP ，能找到 IP 就没问题。

**Comment by ruby186** [comment]
谢谢二位的指点！
