### ISSUE TITLE
高速ip不及一个排, 最后的野战排...

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#139]
黄狗最后的狂奔~~~
LOL

**Comment by wangbingqian** [comment]
多半要凉了……

**Comment by caofengzi** [comment]
嘿嘿。

**Comment by blob2015** [comment]
所以ABC兄说，要支持quic前置 :grinning: 
实在不行，就自己搞vps、某些空间之类了
个人也就用g家的一些东西，fb、tw之类都不怎么耍
在yt出现的各种上传、评论，好像没见减少，都是收编的vpn？

**Comment by jasonliul** [comment]
![y3cjste3jo4x jpg](https://user-images.githubusercontent.com/2461165/42147065-65bb2a6e-7dbb-11e8-9559-b5c1450e1b01.jpg)

**Comment by SeaHOH** [comment]
>在yt出现的各种上传、评论，好像没见减少，都是收编的vpn？

作为重要的资源产地，没有什么能挡住逐利的脚步，墙也不行。

**Comment by MeABc** [comment]
可以下载了， 在 https://github.com/MeABc/zebra-ci/releases 

具体 CI 信息可查看： https://travis-ci.org/MeABc/zebra/builds

特别声明：
1. 做好你现在手头上版本的备份。包括源码，配置等。（以防意外）
2. 一定要使用新的文件夹。（以防意外）
3. 证书兼容，配置大部份兼容。

**Comment by MeABc** [comment]
@blob2015 QUIC 目前还不支持前置。已有思路，不过具体实现时间可不做担保。 :trollface:

**Comment by MeABc** [comment]
关于 sha1sum ，大家可以在 https://travis-ci.org/MeABc/zebra/builds 找到相关版本，查看其 log，拖到最后，其结果类似于下图：

![image](https://user-images.githubusercontent.com/18194126/42167055-6ac4fc4a-7e3f-11e8-9470-e93645a98c45.png)

**Comment by jasonliul** [comment]
@MeABc 
已经用上了, 感觉流畅一点, 不过UI界面没有了以前的大堆提示信息~

**Comment by MeABc** [comment]
@jasonliul 
实际上我也没有做大的改动，提示信息我是有意去掉一部份的。

**Comment by jasonliul** [comment]
@MeABc 
喔~~ 证书问题, 俺在役的是prom. 现在OK了~~

白大少, 换个图标吧, 黄澄澄的感觉古怪, 换个斑马好咧.

**Comment by MeABc** [comment]
@jasonliul 图标这个啊，改是没有问题，但我主要担心的是版权问题。

**Comment by tec1987** [comment]
@jasonliul 万一斑马来找他，你给顶着，哈哈

**Comment by jasonliul** [comment]
@MeABc 
社长已经仙归, 我等正好流氓.

奇怪, 好ip一直下落回零, 白少还需要测试
用prom一直都OK, 主要设置都是照搬的

**Comment by MeABc** [comment]
@jasonliul 

> 好ip一直下落回零

关于这个，如不影响使用，这个都可以不用管了：IP 变 0，会自动复位，重新使用原来的 IPs，不用重启。
同时我这边也会测试的。

**Comment by jasonliul** [comment]
@MeABc 
应该是错误的指示, 因为bad ip并没有增加....
奇怪的bug, 斑马风?

**Comment by blob2015** [comment]
@MeABc ABC兄慢慢来，不急，你这也太帅了，超级帅锅 :grinning:

**Comment by tec1987** [comment]
如果我没记错，这是之前说过的更新了quic-go 的客户端吧？
#115
@MeABc

**Comment by qwertccc** [comment]
我记得客户端的话原来最新的那个是1651啊

**Comment by SeaHOH** [comment]
1651 没源码

**Comment by yeliguo** [comment]
1-TWITTER登陆无法输入密码
2-YOUTUBE视频速度感觉没1651快
3-建议沿用PHUSLU的信息显示  绿色 白色 红色  以前的明了 
     @MeABc   谢谢

**Comment by MeABc** [comment]
@yeliguo 

逐一回复

1. 刚试了一下，twitter 可以正常登陆。
2. 这个不好说，好果确实是我这个版本问题的话，我一时也没有好的主意。
3. 原有的 “绿色 白色 红色”是我有意去掉的，原因有二：
  1）glog 实质已改变，现用的配色正是现 glog 的配色。
  2）接上，现在 glog 的配色再加上 “绿色 白色 红色”乱色很严重，所以就去掉了，以后不可能再加回去了，请见谅。

**Comment by SrS888** [comment]
同样的ip ,youtube速度比1651慢很多。

**Comment by yeliguo** [comment]
@MeABc 明白了 感谢你的付出 黄狗有接班人了

**Comment by MeABc** [comment]
> 同样的ip ,youtube速度比1651慢很多。

可能是我使用了更严格的 IP 筛选策略（HTTP 400 add blacklist ）吧。这个我会关注的。

> 黄狗有接班人了

接班人这种高帽太大，有点吓人。。。。

**Comment by yeliguo** [comment]
对   低调 ：）白少 J哥发的sock前置一直不成功  不知咋回是

**Comment by MeABc** [comment]
@yeliguo 你确定那个 socks 代理可用吗？

**Comment by blob2015** [comment]
@MeABc 估计搞不好又是quic的锅。
配色，个人感觉没啥，稍微适应下。
ABC兄用心了，这个就够了。ABC兄说接班人压力大，这个确实。但不用跟社长比，就当作是自己用的，顺便给他人也用用的小工具，自娱自乐一起乐。

**Comment by blob2015** [comment]
@MeABc 还不会看代码，但记得ABC兄说起过http2与tls 1.3的改进？如果有，那么应该也可以算是主要的提升 :grinning:

**Comment by MeABc** [comment]
@blob2015 
http2 和 tls 1.3 这个工作社长早已做好了，现在不改进，即使算那也是社长的功劳！
GGC 好像支持 tls 1.3 了。不过墙封了 tcp 443 端口，不知道有没有漏网之鱼，如果有那可真是爽歪歪。。。

**Comment by caofengzi** [comment]
@MeABc 發現一個php.json的bug，原文件格式不對所以不能用，原文件格式如下。
{
	"Servers": [{
		"URL": "https://example.com/",
		"Password": "123456",
		"SSLVerify": false,
		"Host": "",
	}],
這樣修改後的可以用了。
{
	"Servers": [
		{
			"URL": "https://example.com/",
			"Password": "123456",
			"SSLVerify": true,
			"Host": "",
		}
	],

**Comment by MeABc** [comment]
@caofengzi 谢谢！已修复。

原来是那样的，我这的垃圾编辑器强制格式化成错误的了。。。。。

**Comment by caofengzi** [comment]
@MeABc githup怎麼不能顯示文件格式縮進呢？老大還需要調整文件縮進啊，因為新版還是不行。




![2018-07-04_183222](https://user-images.githubusercontent.com/13650252/42272762-c769cd60-7fb9-11e8-8a4e-6b0aabcab2b6.jpg)
![2018-07-04_183028](https://user-images.githubusercontent.com/13650252/42272772-cd9a7dce-7fb9-11e8-8b57-f36b0b783ed4.jpg)

**Comment by MeABc** [comment]
@caofengzi 已改，你再试下！

**Comment by caofengzi** [comment]
@MeABc 這個版本ok了。

**Comment by hcym** [comment]
试试这个法器，谷歌下车后如丧家之犬

**Comment by blob2015** [comment]
@MeABc ABC兄，你的source code，底下的两个——zip、tar.gz，都是只有“read me”，好像。

**Comment by tec1987** [comment]
@blob2015 想研究下改动？

**Comment by blob2015** [comment]
@tec1987 一时半会都不会有这能力，就是提一句，可能是ABC兄的某个误操作呢

**Comment by caofengzi** [comment]
@MeABc 老大樓上說的這個：增加 CNIPList （china_ip_list.txt）
增加 CNDomainList （china_domain_list）程序會直接調用嗎？

**Comment by xshzr** [comment]
弱弱问一句，最大连接数在哪设置，单位路由器有限制连接数。

**Comment by caofengzi** [comment]
程序還需要優化啊，和1651對比了一下，還是1651加載網頁的速度快。

**Comment by MeABc** [comment]
@caofengzi 试下 r66 版，这个速度应该会有明显提升（相对 r66 之前，不是 1651）

@jasonliul r66 应该不会狂掉 IP 了。

@xshzr 没有最大连接数选项。

@blob2015 

> source code，底下的两个——zip、tar.gz，都是只有“read me”

谢谢！收到。

**Comment by caofengzi** [comment]
@MeABc 俺這裡用新版沒有j兄說的狂掉ip現象，有時候反而感覺比社長的1651版還多了，俺在試試66速度如何。

**Comment by SrS888** [comment]
r66速度正常了。

**Comment by jasonliul** [comment]
r66 俺这里还是掉ip, 速度倒是与旧版一致~

**Comment by jasonliul** [comment]
@MeABc 
虽然ip狂掉, 令俺心肌重负, 但不像r63, 这个并不影响使用, 恭喜白少, 过渡版本顺利完成~~

**Comment by jasonliul** [comment]
踩~~~
测漏鸟, 野战二排成立

**Comment by jasonliul** [comment]
Tw2
Kr1
Jp1
Id2
La1
Ru3
Bn1
Ph2
Vn2
仅存的亚洲ip ping<200ms
>200ms没了意义, 还不如欧美

**Comment by tec1987** [comment]
。。。你这是IP个数还是段数？
@jasonliul
