### ISSUE TITLE
谁保留得有gogotester最新的那个版本

### ISSUE THREAD

**Issue by mixool** [Kisesy/gscan_quic#14]
在Daocloud上扫了IP[http://gip.daoapp.io/](http://gip.daoapp.io/)  
想用gogotester图形化界面转换下。找不到那个版本了，大佬帮帮忙。

**Comment by Kisesy** [comment]
https://github.com/cannanlly/gogotester

**Comment by mixool** [comment]
谢谢主任！

**Comment by kirbyzhu** [comment]
@mixool 为啥不用ip.html直接转换呢？

**Comment by mixool** [comment]
对哟。。忘了！
gogotester功能多一点，可以收藏
