### ISSUE TITLE
白嫩狗诞生, 送ip

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#142]
103.27.116.0/24
103.85.107.0/24
176.122.86.0/24
176.222.190.0/24
185.191.55.0/24
195.211.180.0/24
212.96.78.0/24
31.148.251.0/24

**Comment by tec1987** [comment]
。。。

**Comment by jasonliul** [comment]
210.19.121.0/24 MY

**Comment by jasonliul** [comment]
这次封杀还蛮彻底...

看起来是基于狗友以前的数据库, 居然没有测漏~ :)

**Comment by blob2015** [comment]
相当彻底了，不过，基于xx数据库的可能更加大些，毕竟易用≈易传播，易传播≈危险。但也不能因此指责xx，毕竟被rape，不能怪长得好看 :grinning: 
只能兵来将挡，水来土淹

**Comment by blob2015** [comment]
再插一句，个人觉得，普渡众生是一种胸怀、包容，但或许，有时候还是要有些取舍，个人觉得，与某门某轮牵扯的，就不要作为目标用户、分享群体了，其余的，求同存异吧，毕竟谁都不完美。
不能以上站街的为目标，站街的，一个劲地让你快快快、爽爽爽，完全没前戏，这样的人，没啥情调啊……

**Comment by jasonliul** [comment]
XX 一直积极收录ip, 宁滥勿缺.
看起来也没有其他数据库这等彻底, 双刃剑.
:)

**Comment by tec1987** [comment]
QUIC可用，绑自定义域名也可以，懒得折腾IP了。
发出来的IP不知道能活多久。。。

**Comment by SeaHOH** [comment]
上个月初我就把 IPv4 清理掉了，现在 XX 所有新版本都用 IPv6。
然后，这几天隧道连接相比以前不太稳定了。

**Comment by Just2co** [comment]
@SeaHOH 你现在也没有用SNI的方式了？国内朋友告诉我最近封的很猛，很多IP都失效了

**Comment by SeaHOH** [comment]
是的，这两天没来得及修改。等会儿绑个证书试试。

**Comment by blob2015** [comment]
@Just2co Just兄去了那国了啊？

**Comment by Just2co** [comment]
@blob2015 肉身翻到了老挝，在这边搞H产，这边稀缺PHP、IOS、前端开发

**Comment by SeaHOH** [comment]
哪儿都不好混。
感觉美帝其实挺羡慕我朝，什么姿势都能玩，百无禁忌。

**Comment by SeaHOH** [comment]
H 产是什么？非业内人士求问。

**Comment by Just2co** [comment]
@SeaHOH 灰产，也就是私彩，跟福彩、体彩呈竞争关系，因为侵犯了既得利益集团的利益，只能在海外合法地区操作这个，避免在国内白干一场，资产清空还得进去。

**Comment by Just2co** [comment]
在国内买体彩、福彩、资金实际上不受监管，被人社部长拿去包十几个二奶，贪几千亿，转移到美国跟瑞士银行。所以国内几千万彩民稍微聪明的，就会选择私彩，赔率高，中奖率高。养活了几十万人在外面搞这个，抓都抓不完，呵呵！

**Comment by Just2co** [comment]
国内反腐，有人相信是真的在反腐吗？国内买彩票会中奖？每天买几百元彩票，没中奖钱去了哪里？他们说他们廉洁奉公，执政为民，有人相信吗？

**Comment by SeaHOH** [comment]
你们公司业务挺宽的嘛，突然感觉钱真好赚。

我不是彩民，因为福彩肯定是有贪污的，反腐后的区别在于钱最后进了谁的口袋。
私彩容易上瘾，不敢玩，数学不行。。。

**Comment by Just2co** [comment]
@SeaHOH 十赌九输，你记得这个几千年不变的真理就行了，跟数学好不好没多大关系，一是运气好不代表次次运气好，所以我选择从来不碰，连平时免费打赌都懒得参与，没意思！

**Comment by Just2co** [comment]
但是就我对这个行业的看法，与其白白送给国内的既得利益，真的不如买私彩的！如果买私彩容易上瘾，买国内的照样可以上瘾的。

**Comment by SeaHOH** [comment]
中奖率高才容易上瘾，但是整体上会亏死。。。

**Comment by Just2co** [comment]
嗯，把最近这几条删掉，不确定网 监有没有用爬虫实时检测这些讨论区，被他们抓取到封存证据就麻烦了

**Comment by jasonliul** [comment]
171.255.205.0/24 VN
似曾相识, 但不在各大数据库内

**Comment by jasonliul** [comment]
188.234.156.0/24 RU

**Comment by blob2015** [comment]
@jasonliul 摸奖的效率很高，其实是一个接近于最优解的解。恭喜J哥从排长荣升为连长。

**Comment by nxtreaming** [comment]
请关闭此issue, 这里不是喷子们抒发感情、指点江山的地方。
-----------------------------------------
Productive. Reliable. Fast.

**Comment by tec1987** [comment]
@blob2015
早已不需摸奖，直接查数据库。。。

**Comment by blob2015** [comment]
@tec1987 还有数据库？怎么说？

**Comment by tec1987** [comment]
@blob2015
有不少做v4全地址扫描的，并且提供相关数据。
但是方法不便公开（至今网上也没有人发），免得墙奴拿去邀功。
