### ISSUE TITLE
摸奖 谷皮V6

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#144]
2A02:148:C:99C2::E|2A02:3040::7::E|2A02:130:9900:80::E|2A02:C7A:8000:F102::F|2A03:F680:FCFF::C|2A02:A47F:E000:8::12|2A02:2148:8FFF:FF00::11|2A0B:880:1::C|2A0B:880:1::D|2403:6200:FFFF:FFB2::D|2403:6200:FFFF:FFE0::12|2403:DD00:A:2::D|2A00:7600::1000::C|2A00:1CB8:2:6::E|2A00:1CB8:2:6::F|2A00:1D50:6::E|2A00:1EB8:E000:103::C|2A00:1EB8:E000:103::D

**Comment by SeaHOH** [comment]
IPv6。。。好像是第一次耶。
其实 IPv6 干扰也增多了，不知道那些 xbox 玩家有啥想法。

**Comment by jasonliul** [comment]
@SeaHOH 
滚~~~
海少是煞风景专业户.
LOL

**Comment by jasonliul** [comment]
2A02:3040::4::E|2A02:770:3F20:FFFF::E|2A02:8400::104::F|2A02:8400::10D::13|2A02:8400::118::F|2A02:A47F:E000:11::13|2A02:FE0:1:6008::E|2403:5000:171:24::E|2A00:4520:1:5::C|2A00:4520:2:4::C|2A00:1CB8:2:3::D|2A00:1CB8:2:8::11

**Comment by jasonliul** [comment]
202.40.221.41|2A02:C7A:8000:206::10|2A02:2028:1002:5::D|2A02:2148:8FFF:FF00::D|2A02:8200:1:9::D|2A02:148:D:99C2::E|2A02:8200:1:9::C|2A02:16D8:2:1E::D|2A02:2028:1002:1::10|2A02:2028:1002:1::D

**Comment by blob2015** [comment]
感谢J哥，开启V6尊享版 :grinning: 
大海兄对V6还是比较了解的

**Comment by yogaskung** [comment]
ipv6都可以干扰，🤯震惊

We are Microsoft, the resistance is futile, you will be assimilated, the strongest script is no exception!

**Comment by SeaHOH** [comment]
IPv4 已经开始全面检查 ServerHello 的证书域名了，之前只检查 ClientHello。
IPv6 隧道还看不出来是如何判断的，感觉像是跟前几年的 IPv4 类似，根据流量来判断。
