### ISSUE TITLE
python2.7 功能请求

### ISSUE THREAD

**Issue by fuckchinaOK** [Kisesy/gscan_quic#149]
有个txt文本，每行一个IP。

把每行的IP拿出来，到下面这个网址查询。

https://ip2c.org/?ip=114.114.114.114
1;CN;CHN;China

https://ip2c.org/?ip=8.8.8.8
1;US;USA;United States
......

最后把所有的查询结果，输出到  结果txt文本
格式大概如下：
114.114.114.114  CN;China
8.8.8.8  US;United States
......

**Comment by fuckchinaOK** [comment]
已经解决了，  原来需要的功能，只要50行左右的代码，就可以做到了！
虽然是python新手，但是相信经过研究。我自己可以做出这个功能！

**Comment by tec1987** [comment]
你没问题吧？？？！
