### ISSUE TITLE
遍历ip range?

### ISSUE THREAD

**Issue by fredericky123** [Kisesy/gscan_quic#16]
能否设置为遍历iprange后输出满足条件的所有ip，而不是输出固定数量？辛苦大大

**Comment by Kisesy** [comment]
你把数写大一点不就行了，写个1000万，你也跑不出这么多啊

**Comment by fredericky123** [comment]
好的，只是不确定写大数是否会导致达不到数目一直扫下去

**Comment by fredericky123** [comment]
是的，试验了下，数量级足够大就能遍历，gscan 能正常输出

**Comment by NAVrasZ** [comment]
是否能加入随机扫的功能？例如5000的话，大家用同一份iprange，结果都在用前面的ip
