### ISSUE TITLE
Z180已然超過社長贈別版本, Goproxy榮休!

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#165]
Quic模式穩定性超過末版GP, 幾乎不再有連接無端失效, 需要重刷的情形...
從66到180, 白少辛苦喇, 看茶~~~

IP方面, 已然有掉落的問題, 但是可以自動恢復增長. 
如果把設置項基本比齊社長舊版, 這種現象完全不影響使用.

看來是白少更注重效率, 社長偏於保守, 電信用戶可能更合適社長的設置值.

**Comment by SeaHOH** [comment]
:heart:  :+1:

**Comment by jasonliul** [comment]
@SeaHOH 
還以為你只玩XX喇... :)

**Comment by SeaHOH** [comment]
帮忙修补而已，毕竟还有人愿意用。
不过，可能用不了多久了，谷格愈来愈危险的感觉，不知道会不会突破底线。

**Comment by wpyok500** [comment]
呜呼哀哉，善莫大焉。

**Comment by wpyok500** [comment]
z 什么时候能支持ipv6的quic ???

**Comment by tec1987** [comment]
Google跟GFW耗了这么多年，恐怕没兴趣再耗下去了。。。
毕竟人家是商业公司

**Comment by jasonliul** [comment]
@SeaHOH 
免驚, 川普大大盯得緊~~~ LOL

**Comment by AnyWAT** [comment]
同一网页若干图片，Z180加载不全（貌似没报错，只有少许空白，与网页明确的若干不符），但XX-Net 则不会😂

**Comment by jasonliul** [comment]
@AnyWAT 
火狐沒有這問題...

**Comment by AnyWAT** [comment]
正是FF62.0.2😜 Chrome 没试

**Comment by SeaHOH** [comment]
@jasonliul 
虽然这么说有点不好，我觉得自己倒是没有啥问题，但是其他大牛们还是要注意一下。
下面这段话是先前写的，然后想着这里说没啥意义，现在还是发出来说明下我的想法。

---

希望它能有它所标榜的商业公司的操守，毕竟这边的手段还是很厉害的，只要不怕那极小的泄露可能，不然随便配合搞几个人是非常简单的。
假如某人被卖去喝茶，他很可能不会意识到或无法肯定是怎么暴露的。
当然，实际过程不会这么直接简单，如果隔离层数足够，也不一定能挖到底。
但不是每个人都会做这么完备的防护措施，而且只要有足够多数据就可以进行指纹和画像，简直防不胜防。
大牛们可能即将面临严峻的考验，急需提高隐身技能。

**Comment by AnyWAT** [comment]
删除了 cache 再启动Z180，第一次显示8/17，刷新，程序窗口停止刷频，出错，托盘右键“重新载入”，刷新出17/17😂

**Comment by jasonliul** [comment]
@AnyWAT 
火狐讀取緩存的能力不如穀殼類....
清除火狐緩存, 使用"強制刷新"功能~~

gae.json
"Level": 8,  改小這個為8, 或12, 16, 默認20對於電信線路太高~~

**Comment by jasonliul** [comment]
IP應該是40-50個, 我這裡ip浮動<35個, 因此起碼要40個可用ip.

**Comment by jasonliul** [comment]
火狐支持pipelining
about:config
network.http.pipelining，双击赋值为true
network.http.pipelining.maxrequests，双击并赋值为8
network.http.proxy.pipelining，双击并赋值为true

開啟流水重試, 可以大幅提高代理穩定性, 也適用其他代理程序.
不過有時會多一些人機驗證 .... :)

**Comment by yfdyh000** [comment]
@jasonliul 随着HTTP 2时代，Firefox的H1 Pipeline已经删掉了。
https://bugzilla.mozilla.org/show_bug.cgi?id=1340655

**Comment by AnyWAT** [comment]
谢谢楼上二位！
老台机，时常扩展 Clear Cache，只不知"強制刷新"功能在哪？
非電信的移动線路，是否也得改小 gae.json ？
"Level": 8
IP现在几次 gscan 有80個
正如楼上说的，没搜索到那几个参数
開啟流水重試：老白不明是啥😭

**Comment by AnyWAT** [comment]
@jasonliul 基本还能有效的GoProxy r1624的 gae.user.json（貌似只有导入XX-Net 扫描出的 IPv6才基本正常），而复制到Z180只能导入 gscan 出的 IPv4才正常，但某些参数一致如下，请教：是否有误？
	"SSLVerify": false,
	"DisableIPv6": false,
	"ForceIPv6": false,
	"DisableHTTP2": true,
	"ForceHTTP2": false,
	"EnableQuic": true,
	"EnableDeadProbe": true,
	"EnableRemoteDNS": false,

**Comment by tec1987** [comment]
”DisableHTTP2“: false
试一下

**Comment by qwertccc** [comment]
z的 服务端怎么上传啊？

**Comment by tec1987** [comment]
项目自带文档说明
@qwertccc

**Comment by tec1987** [comment]
@AnyWAT 去项目源码库找

**Comment by blob2015** [comment]
@jasonliul 
> "Level": 8, 改小這個為8, 或12, 16, 默認20對於電信線路太高~~
俺提醒一句，别说电信，移动的话，level耐艹更差，建议初选、再选ip之后，改为≤4，否则会影响正常网页的打开

@SeaHOH 
单纯依靠技术，除非是巅峰的几个人，或者团体，否则，都是很难的，个人感觉，不要追求“绝对”，这会给自己绝大的压力。自己稍微注意点就是了。大海兄也是敏感的人，敏感的人，会想很多，有时候，也容易成为惊弓之鸟（虽然有时候确实有危险）。
平常心，平常心。

**Comment by jasonliul** [comment]
IP 慢慢恢复, 不少旧字段已经渗漏可用~~

**Comment by SeaHOH** [comment]
是的，因为这个有人跑去 XX-Net 骂默认设置不给用 IPv4。 :smiley_cat: 
感觉下个版本可以试试水，毕竟用户数量那么大。

**Comment by jasonliul** [comment]
@seahoh
你这是自杀....

单纯添加俄国, 印度去试水, 现在印度ip似乎比从前好用很多. :)

**Comment by blob2015** [comment]
@SeaHOH @jasonliul 
附议J哥
开一扇窗，从无到有，从易到难，方便自己、同时也顺便方便一下别人，慈悲心，善业
但不要太过放任，他们一时爽，但很容易不经意间给谁（比如社长 @phuslu ）惹来不必要的麻烦，细水长流才是王道
救急另当别论
把ip限制在阿三、毛子，算是一个可以操作的提议——或者再加个别南亚的国家
