### ISSUE TITLE
新玩具 PenguinProxy 

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#167]
https://www.penguinproxy.com/

p2p 社區VPN, 
You can equate it to using a public Wi-Fi hotspot. So, it is advised to use PenguinProxy along with HTTPS Everywhere to obtain end-to-end encryption.
 
PenguinProxy only supports HTTP (web browser) traffic, it does not work for OpenVPN, SOCKS, Bittorrent, SMPTP or other protocols.

**Comment by blob2015** [comment]
感谢J哥

**Comment by 2378** [comment]
:bouquet::bouquet::bouquet::bouquet::bouquet::bouquet:

**Comment by xugaohui** [comment]
@jasonliul 谢谢分享，这个软件使用一段时间了。如果是在线看视频,720p很免强 速度1500kbps。用于下载软件，还是很好的用的，不限制多块连接数，下载速度十分快，一般都可以跑满30M光纤。只支持http代理,不支持https,socks5。不支持Proxifier 3.42。作者不知道中国人的习惯，有些方面一直不改。软件下载后，需要自己精简做成绿色版。需要编辑app.asar文件十多处，禁止开机启动。禁止强制设置ie代理连接。
总结，如果需要大量下载，这个软件还是很好的。
现在改用VPN Gate ，真正的高速。

**Comment by jasonliul** [comment]
[url=https://www.penguinproxy.com/static/download/PenguinProxy.exe] [b]PenguinProxy 0.1.2[/b] [/url]

**Comment by jasonliul** [comment]
@xugaohui
你可以做个绿色版本, 群友同享~~

**Comment by jasonliul** [comment]
https://www.bestvpnrating.com/review/penguinproxy
相关评测

**Comment by xugaohui** [comment]
> @xugaohui
> 你可以做个绿色版本, 群友同享~~

如何安全的分享呢?自己的记录早被收集了.

**Comment by AnyWAT** [comment]
ICQ？
