### ISSUE TITLE
https:/en.wikipedia.org to https://zh..

### ISSUE THREAD

**Issue by yogaskung** [Kisesy/gscan_quic#168]
Chrome 67.0.3396.87
Android 6.0.1
I am looking en.m.wikipedia.org,and i searched 强迫症 (chinese),and then there are
pages in zh wikipedia,i turn in,well,there are nothing connection question.
Very interesting. 
![Screenshot_2018-10-01-13-25-29-923_Chrome.png](https://i.loli.net/2018/10/01/5bb1b0673db1f.png)
![Screenshot_2018-10-01-13-25-16-605_Chrome.png](https://i.loli.net/2018/10/01/5bb1b0678b4d2.png)
![Screenshot_2018-10-01-13-25-21-128_Chrome.png](https://i.loli.net/2018/10/01/5bb1b0684089b.png)
![Screenshot_2018-10-01-13-25-45-710_Chrome.png](https://i.loli.net/2018/10/01/5bb1b06850f28.png)
![Screenshot_2018-10-01-13-25-39-690_Chrome.png](https://i.loli.net/2018/10/01/5bb1b068c920a.png)

**Comment by yogaskung** [comment]
btw i dont use any hosts or vpn.

**Comment by SeaHOH** [comment]
估计是没有第二次握手，重用了 en 的连接。
你可以保持 en 的页面不关闭，把网络断开几秒钟再点击 zh 的链接，看这样能否打开。

**Comment by yogaskung** [comment]
Yes,you re right.And that means one could access zh.wikipedia with no
limition as long as they go to en.wikipedia time to time :)

**Comment by tec1987** [comment]
TLS会话重用，就是这样
https://zh.wikipedia.org/wiki/Help_talk:%E5%A6%82%E4%BD%95%E8%AE%BF%E9%97%AE%E7%BB%B4%E5%9F%BA%E7%99%BE%E7%A7%91
