### ISSUE TITLE
zebra CustomDomains

### ISSUE THREAD

**Issue by THLIVSQAZ** [Kisesy/gscan_quic#170]
zebra 的自定义域名貌似无法使用,并不格式问题
![screenshot from 2018-10-14 00-34-42](https://user-images.githubusercontent.com/25531652/46907693-06e47d80-cf49-11e8-8fd9-ea9ef2cf0eae.png)

**Comment by MeABc** [comment]
收到。但现在没有时间解决，稍等。你可以先用 goproxy 。

**Comment by THLIVSQAZ** [comment]
好的，谢谢MeABc大大
