### ISSUE TITLE
SSTAP 修订版 by sang8052

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#173]
通过钩子捆绑QQ的UDP端口发送数据，避免部分地区防火墙阻断UDP的数据（程序运行前请先登录QQ）
软件里内置两条免费的香港线路

链接：http://pan.szhcloud.cn/s/04gy1i0m   密码：jf23ib

**Comment by 2378** [comment]
程序运行前请先登录QQ :u7121: :secret::secret:

**Comment by blob2015** [comment]
真是奇技淫巧 :grin
感谢J哥
