### ISSUE TITLE
Free VPS, DIY 必备

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#176]
Free VPS

https://www.solvps.com/free-windows-vps/
http://vpswala.org
https://gratisvps.net/
http://ohosti.com/vpshosting.php
https://www.zettagrid.com/cloudcomputing/30-day-free-trial/
https://centerhop.com/vps/unmanaged-vps/

**Comment by fredericky123** [comment]
又见J大 
Me大咋不更新一下zebera了呢 大家都哪玩去啦

**Comment by jasonliul** [comment]
https://github.com/lucas-clemente/quic-go/releases
上游没有更新

**Comment by fredericky123** [comment]
Let's wait 😜

**Comment by 2378** [comment]
感谢J大 感觉谷歌要交投名状了

**Comment by jasonliul** [comment]
未必, 不过quic其实很容易干扰~~
夜间那些谷云搭建的ssr同样瘟鸡.

近期政情极度敏感, 破墙癫狂也属意料之中

**Comment by 2378** [comment]
不是最好:cry: 反正最近各种梯子，备用的潜伏的都启用了

**Comment by jasonliul** [comment]
现在的ssr已经变味, 留意那些自带审计[审查]的所谓提供商.
不过ssr本质也还是socks前置, 可以用其他的穿透来用

**Comment by SeaHOH** [comment]
再过几天就明了了。

**Comment by jasonliul** [comment]
会玩vps的,可以试试这个
Chisel 1.24
https://github.com/jpillora/chisel/releases

也属高效代理, 而且国内没人尝鲜过, 开发相当稳定

**Comment by jasonliul** [comment]
@SeaHOH
该改就改不该改坚决不改, 
全世界媒体都有这句, 这等于全面宣战国内国外~~

不用再等,情形只会恶化.

**Comment by AnyWAT** [comment]
😱被人看不上的 wujie 正常中

**Comment by jasonliul** [comment]
@AnyWAT
UltraSurf的信用归Alen Huang[黄云], 原89六位学生, 后任职硅谷软件工程师.
此人曾在US国会作证, 是相当被瞩目的人物.

UltraSurf 在德荷俄, 很多网安小组测试过, 并无值得担忧的.

**Comment by AnyWAT** [comment]
谢谢大佬，学习了😋

**Comment by SeaHOH** [comment]
> 被人看不上的 wujie 正常中

并没有看不上，只是大家都愿意把它作为备用而已。

**Comment by jasonliul** [comment]
中国人闭幕塞听而已.

软件的信用归属作者, 并非赞助者. 文明世界是讲究诚信度的, 不同我朝毫无底线

**Comment by jasonliul** [comment]
UltraSurf 使用的服务商也相当有名, 当年德国Jondo[欧版Tor 洋葱]开发美洲市场的合作方, 也是美国最有实力的网络安全提供商之一.

**Comment by blob2015** [comment]
俺这边，g的首页也是打不开的

**Comment by jasonliul** [comment]
使用sockscap64, 选一个前置. ssr/ss都行

取消quic设置, 
填写45.64.20.0/24
103.192.46.0/24
202.86.162.0/24 作为ip段落, 再试~~~

看起来这像谷歌自家的出问题, 并非封杀

**Comment by jasonliul** [comment]
@caofengzi
能够使用Google主页, 当然不是封杀~~ :)

**Comment by blob2015** [comment]
感谢J哥，俺就暂时歇歇手吧

**Comment by jasonliul** [comment]
再加一个
https://console.bluemix.net/registration/

**Comment by xugaohui** [comment]
这个也不错，VPN Gate Client

**Comment by tec1987** [comment]
mark
bluemix注册过，太复杂，没玩明白。。。
