### ISSUE TITLE
老版迅雷极速

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#179]
老版迅雷极速
https://www.jayxon.com/thunder-speed-1-0-11/comment-page-1/

作者达人, 居然保存在国外网盘, 所以幸存.

**Comment by blob2015** [comment]
感谢J哥
俺用的是1.0.34.360，都是要下载的时候再安装，下载完毕后，就删除

**Comment by AnyWAT** [comment]
删除，免费绿色的 Autoruns 禁用开机启动及服务不就行了？

**Comment by blob2015** [comment]
@AnyWAT 
下载关闭后，后台有进程啦……
迅雷可不是吃素的……

**Comment by AnyWAT** [comment]
软媒魔方不也是？ Autoruns 搞定

**Comment by jasonliul** [comment]
迅雷其实是设置系统文件夹.

cmd[管理员]  attrib X:\TDDownload -s

**Comment by jasonliul** [comment]
@blob2015
这个版本很干净, 后续版本才加了一堆垃圾
