### ISSUE TITLE
☆☆☆ 社长的黄狗, 今日荣休~~

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#180]
谷歌始乱终弃, gae被休妻~~~

终于到了黄狗荣休的日子了, 几分不舍.

**Comment by caofengzi** [comment]
看xx的反饋也是有好有壞。

**Comment by jasonliul** [comment]
社长是佛徒, 有生必有灭, 
何必死抱惯性惰性~~
:)

**Comment by SeaHOH** [comment]
感觉 XX 也要凉，就那么几个 IP，还像之前一样扫，谷歌会封吧。

**Comment by jasonliul** [comment]
12日谷歌被国会炮轰
https://theintercept.com/2018/12/11/google-congressional-hearing/

Google公司CEO Sundar Pichai，在美國國會強調，目前該公司沒有重返中國市場的計劃。

回头谷歌觉得GAE给中国番茄党, 白白啃食多年. 无数白花花的流量, 尽付东流~~

也无怪得这次阉掉GAE... 毕竟谷歌是商家, 不是慈善家.

**Comment by SeaHOH** [comment]
> 毕竟谷歌是商家, 不是慈善家.

早就讲过这个理，但大多数态度都是：谷人希~

**Comment by jasonliul** [comment]
中国人利用GAE大规模做代理, 本来属于滥用行为, 不过谷歌视为让利, 促销广告一类. 用来保留潜在中国市场客户.

今年针对中国定制的审查版引擎蜻蜓, 员工几次游行抗议, 谷歌装懵, 几位议员, 副总统炮轰, 谷歌扮傻. 反正并不违法.

但是国会听证是民主国家最高阶的公众舆论监督, 成为美国焦点事件, 就连总统也怕几分. 谷歌无奈割肉认栽 放弃蜻蜓计划.

研发搁浅的蜻蜓 + 多年GAE让利 = 数目可观的净亏损.

谷歌只是做了任何公司都该做的事 -- 损害控制. 其实无可非议~~

**Comment by hcym** [comment]
现在做搬瓦工很安逸，还是要感谢社长和主任，还有各位扫地僧。哈哈

**Comment by jasonliul** [comment]
无良~~~:)

首先致谢的该是狗族金主, 为富且仁google公司.

**Comment by hcym** [comment]
这个不用说了，祝谷歌寿命更长，肯定比gfw长，奶奶的

**Comment by jasonliul** [comment]
@SeaHOH
未必, 不过得缩减狗族规模.

二狗Gogotunnel已经著草, 搭建SNI能够继续XX, 况且目前仅有的几百ip, 质量可悲.
好歹SNI可以让传输更加流畅~~~

如果添加前置Socks4支持, 可以加速传输. 必须是socks4, 才有一些稳定多年的免费节点.

**Comment by SeaHOH** [comment]
我还是决定专注于伪装 SNI，GAE 就随缘了。

**Comment by jasonliul** [comment]
SNI也是站长们的宝贝, Gogotunnel拿来番茄, 结果被封杀, 也有无数骂娘声~~
适可而止.

**Comment by SeaHOH** [comment]
是伪装 SNI，不是使用 SNI-Proxy。。。

**Comment by jasonliul** [comment]
没有"发死噜"社长在这里啤酒同庆, 感觉真不是滋味~~

**Comment by jasonliul** [comment]
@SeaHOH
fake SNI will no longer work with google front server, no SNI is ok.
原来假冒贼就是你, 卿本少爷, 奈何做贼? :)

**Comment by SeaHOH** [comment]
不是指谷歌服务，而是没有封 IP 的其它网站，大多数都能连上。

**Comment by jasonliul** [comment]
@SeaHOH
该集中一下那些刷路由器的帖子了, 原生IPV6应该还可以玩很久.

国内的路由器几乎都是仿造台版, 而台湾那几家本来就支持刷入.
校园网有若干流氓无产者疯狂刷过, 教程多得很. 刚看了一下, XX组也有几篇.

还需要海少振臂~~ 否则天天哀嚎, 也就没得玩咧.

**Comment by SeaHOH** [comment]
我没有使用更多功能的路由器的需求，所以不会做这个事，反正有教程，大家照着做呗。
正在努力实现可以直连所有没直接被封 IP 的站点的方案。

**Comment by jasonliul** [comment]
@SeaHOH
很多地方都已经开通ipv6, 不过还得靠路由器分支, 国产路由器大多不支持ipv6,
刷入ipv6支持其实很简单, 只是多数人搞不懂"刷路由器"是什么意思.

校园网最早有ipv6, 因此很多人都玩过.
搞懂步骤其实就几分钟, 原生ipv6, 不需要4to6隧道

**Comment by SeaHOH** [comment]
不用刷，光猫就支持，前提是要登录进去。。。破不了才需要买路由器。

**Comment by jasonliul** [comment]
新装的才有吧?
俺好像觉得很多人都是刷的

**Comment by SeaHOH** [comment]
光猫应该都支持，买的路由器才是很多不支持。
我的无线路由就是最便宜那种，一直当集线器用。

**Comment by jasonliul** [comment]
@SeaHOH
XX-net/XX-Net#11775

你那边ipv4反正没用, 怎不捐献完整列表过来?
这些俺这里扫不出支持quic的...

或者全都不支持?

**Comment by AnyWAT** [comment]
> 你那边ipv4反正没用

貌似有用：此时 X-Tunnel 的 Cloudflare 前端才正常

**Comment by jasonliul** [comment]
俺试过使用这些IP, tcp方式, 前置一流, 
可以用, 但是光火的是中国Google ip就无效了, 下载相当可怜. 哈~

**Comment by SeaHOH** [comment]
@jasonliul 你是指 GAE？反正就那么几百X2 个，不过都支持 QUIC 和 H2 了。

**Comment by blob2015** [comment]
默哀三秒钟，一鞠躬 :)
感谢社长，感谢诸位 :)

**Comment by jasonliul** [comment]
@SeaHOH
俺从来没有用过这类铜IP, 即使最恶劣的时期, 起码3枚白金ip. :)

搞几枚可用的quic给余孽们而已~~

**Comment by dou4cc** [comment]
上香.

**Comment by jasonliul** [comment]
@dou4cc
嘢~~~
以为你嘢化为狼去咧.

**Comment by jzp820927** [comment]
@SeaHOH 伪装 SNI，还是挺有前途，能复活一大批网站，啥时候能发布一个测试版？我第一个来测试？

**Comment by dou4cc** [comment]
@SeaHOH https://twitter.com/bluebit_cg/status/1059316910913998848

**Comment by SeaHOH** [comment]
@jzp820927 
这两天正是忙的时候，空闲时间大多用来追剧了，修改进度比较慢。。。
其实现在也能用，就是安全方面不过关，GAE 模块也会影响正常使用，不过可以停用 GAE 代理。

@dou4cc 
谢谢提供信息。不过感觉还没有到需要这么极端办法的时候，毕竟伪装 SNI 还是能用的。

**Comment by blob2015** [comment]
@SeaHOH 
大海兄，追的啥剧咧

**Comment by jasonliul** [comment]
@SeaHOH
骗子, 美剧已经休歇.

新店几时开张?

**Comment by SeaHOH** [comment]
好吧，我承认是骗子，其实是在补剧。
元旦过后两三天内估计能改完。

**Comment by blob2015** [comment]
@SeaHOH 
还是大海兄啊
不过，补啥咧，这年头，好剧少啊，常年剧荒中

**Comment by SeaHOH** [comment]
具体啥剧就不说了，这并不重要，毕竟不是讨论这个的地方。

**Comment by jzp820927** [comment]
@SeaHOH 看了下，你目前的 gotox 项目，没看到关于 伪装 sni 的相关说明。具体怎么配置使用？另外，我想问一个比较重要的问题。是不是原生证书？不会像 GAE 一样，要 fake 证书吧？如果不是原生证书，那限制就很大了，基本上移动设备 apps 都用不了了？

**Comment by blob2015** [comment]
@SeaHOH 
大海兄一如既往腼腆 :)

**Comment by jasonliul** [comment]
淫贼~~~
想要姑侄恋?

**Comment by SeaHOH** [comment]
@jzp820927 
说明在规则配置文件中有写，但是 readme 还没有更新。
我这个实现很简单，伪造 SNI 必须使用假证书，局限性较大。

也许你想试试这几个：

https://github.com/seclab-ucr/INTANG
https://github.com/ValdikSS/GoodbyeDPI （win）
https://github.com/bol-van/zapret
https://github.com/Macronut/SNI-Mask

**Comment by jzp820927** [comment]
@SeaHOH 好的，谢谢推荐。我研究下。

**Comment by SeaHOH** [comment]
不好意思，先前说元旦完成，结果我今天才弄完。

附带的 IP 没有更新，可以自行扫一些替换。
IPv4 和 IPv6 都可以使用，数量都比较少，IPv6 更稳定些。
筛选参数不要调地太夸张，根据自己的网络条件来修改。

另外，可能会有许多 bug，如有可能请尽量告诉我。 :smile_cat:

**Comment by wooowooo** [comment]
1。蜻蜓没了，狗停止慈善 
2。许多用户反应墙更高
这两件事同时发生，是独立事件还是有关联？

**Comment by mixool** [comment]
赶上热乎的了，我来重拾一下，感谢SeaHOH

**Comment by jap33** [comment]
v

**Comment by SeaHOH** [comment]
https://github.com/SadeghHayeri/GreenTunnel
对了，发现个 SNI-bypass 新项目，Node 的，执行效率应该很高，感兴趣的可以试试。

**Comment by jasonliul** [comment]
@SeaHOH
狗没了, 雕没了...
人也没了~~~

你还在这里做啥子?

**Comment by SeaHOH** [comment]
随缘？ :smiley_cat:

**Comment by jasonliul** [comment]
@SeaHOH
这个调调, 很快会闪婚~~~
:)
