### ISSUE TITLE
☆☆前置斑马~~~

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#184]
Socks5
156.239.58.3:1080
156.239.58.5:1080
156.239.58.8:1080
156.239.58.4:1080
156.239.58.10:1080
156.239.58.9:1080
156.239.58.7:1080
156.239.58.6:1080
都是大带宽
"Proxy": {
	"Enabled": true,
	"URL": "socks5://x.x.x.x:1080",

IP
https://github.com/XX-net/XX-Net/issues/11775

填写google_hk段落
修改gae.json
	"EnableQuic": true, 改为false
删除"google_cn": 全段
搜索"google_cn"替换为"google_hk"

玩去吧~~~

现在谷歌的新策略, 使用前置的话, 中国google ip不再能够帮忙. 直连才能起作用.
警告: google_hk 段落里面不能添加非GAE的任何一个ip, 否则照样出错~~~
![screenshot 1](https://user-images.githubusercontent.com/2461165/50409740-d5abe780-07ec-11e9-8f39-793736e67a59.jpg)

**Comment by jasonliul** [comment]
https://github.com/XX-net/XX-Net/issues/11775

**Comment by ruby186** [comment]
{
    "type": "localproxy",
    "host": "[::]:8087",
    "software": "goproxy r1623 (go/devel +9ee40de927 Sun Sep 24 09:14:54 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "GAE: cannot reach here with &http.Request{Method:"GET", URL:(*url.URL)(0x1f2e0640), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Dnt":[]string{"1"}, "Accept":[]string{"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"}, "Accept-Encoding":[]string{"gzip, deflate, br"}, "Accept-Language":[]string{"zh-CN,zh;q=0.9,en;q=0.8"}, "User-Agent":[]string{"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36"}, "Upgrade-Insecure-Requests":[]string{"1"}, "Cookie":[]string{"UM_distinctid=166df4f5a3fd2-014680167b07af-5c10301c-100200-166df4f5a40243; solidot_theme=green; CNZZDATA1864685=cnzz_eid%3D40798796-1525590509-%26ntime%3D1545658820; Hm_lvt_d11396a350156e4682e4156a671bdaf1=1545622966,1545628853,1545630682,1545662825"}, "Connection":[]string{"keep-alive"}, "Cache-Control":[]string{"max-age=0"}}, Body:http.noBody{}, GetBody:(func() (io.ReadCloser, error))(nil), ContentLength:0, TransferEncoding:[]string(nil), Close:false, Host:"www.solidot.org", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"127.0.0.1:18526", RequestURI:"/", TLS:(*tls.ConnectionState)(0x1f286900), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:(*context.valueCtx)(0x1f3eee20)}"
}

**Comment by blob2015** [comment]
感谢J哥

**Comment by ruby186** [comment]
报告，已失效
