### ISSUE TITLE
☆弃狗玩雕 必备

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#185]
Servers
http://shadowsocks.org/en/download/servers.html
 
Deploy easy
https://blog.wtigga.com/shadowsocks/
https://github.com/jlund/streisand
 
Ссылаться на
https://blog.wtigga.com/streisand-vpn/
 
Free VPS
https://www.solvps.com/free-windows-vps/
http://vpswala.org
https://gratisvps.net/
http://ohosti.com/vpshosting.php
https://www.zettagrid.com/cloudcomputing/30-day-free-trial/
https://centerhop.com/vps/unmanaged-vps/
https://console.bluemix.net/registration/
 
Client
https://github.com/shadowsocks/shadowsocks-windows/releases
 
shadowsocks 4.0.5
https://github.com/shadowsocks/shadowsocks-windows/releases/download/4.0.5/Shadowsocks-4.0.5.zip
 
shadowsocks 4.0.7
https://github.com/shadowsocks/shadowsocks-windows/releases/download/4.0.7/Shadowsocks-4.0.7.zip
 
-----------------------------------------------------------------
ShadowsocksR /SSR [Shadowsocks + Obfuscation]
Servers
https://github.com/shadowsocksrr/shadowsocksr/tree/akkariiin/master
 
Client
https://github.com/shadowsocksr-backup/shadowsocksr-csharp
 
ShadowsocksR 4.70 Final
https://github.com/shadowsocksr-backup/shadowsocksr-csharp/releases
 
Join here for any help about Shadowsocks/ShadowsocksR
https://t.me/joinchat/EgQZm0EIwMNB8tQzM6OpOw
 
------------------------------
Free account info
tg  
https://t.me/shareproxyfree
https://t.me/IRANSSR
https://t.me/linkSSR
https://t.me/sslist
https://t.me/SSRlist
 
https://plus.google.com/communities/110896176697381748150
https://plus.google.com/communities/103542666306656189846
https://plus.google.com/communities/104092405342699579599
https://plus.google.com/communities/106591655000979844194
https://plus.google.com/communities/111481001872828692486
https://plus.google.com/communities/100696601043951646379
https://plus.google.com/communities/112474836283977223682
https://plus.google.com/communities/110135260775165290676
https://plus.google.com/communities/105376720190385819703
https://plus.google.com/communities/117702818760720009772
https://plus.google.com/communities/109962494203239446911
https://plus.google.com/communities/116546712812972318676
https://dotblogs.com.tw/axutongxue/2018/04/05/ssr
 
https://free-ss.site/
https://ssray.club/
https://ss.freess.today/
https://www.ssrtool.com/tool/free_ssr
https://io.freess.org/
https://la4ji.blogspot.com/2017/09/shadowsocks-shadowsocks.html?m=1
https://gdmi.weebly.com/3118523398online.html
https://a.ishadowx.net/
https://abc.ss8.fun/
https://shadowsocksr.cat/

Free service from Canada
https://www.freevpn.center
*You need download client software from them, and need register.
 
Get invite code
Google search, copy/paste:
&#36992;&#35831;&#30721; inurl:/code.php

**Comment by xugaohui** [comment]
VPN Gate上大量SoftEther VPN，L2TP/IPsec，OpenVPN 和 MS-SSTP
随便找一个,油土拨速度上万.早该弃用zebra了.

**Comment by jasonliul** [comment]
@xugaohui
国人还在意淫大清国, 动辄抵制洋货~~ :)

**Comment by jasonliul** [comment]
@xugaohui
印尼, 俄国玩softether是俺推介的, 他们也有一些免费节点, 非VPNgate
https://www.fastssh.com/page/softether-servers
http://www.vpnjantit.com/free-softether.html

google定向搜索还有更多~~

**Comment by blob2015** [comment]
感谢J哥

**Comment by AnyWAT** [comment]
2019继续折腾黄狗…… #188

**Comment by Tino23X** [comment]
@xugaohui  请问一下VPNGate 上面的要如何使用呢？用SoftEther VPN Client 完全连不上啊。 各种梯子都挂了，现在很郁闷啊。
