### ISSUE TITLE
☆☆☆外卖时代, 前置代理极简速成

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#186]
前置代理等于外卖哥, 直接就餐已经out, 遣返石器时代. 外卖哥国内通常称为正向代理, 二级代理...

分两种:
◇ Socks4/5 袜子代理
快速获取袜子代理
http://proxysearcher.sourceforge.net/Proxy%20List.php?type=socks
http://www.gatherproxy.com/sockslist

快速检测袜子代理
http://www.checker.freeproxy.ru/checker/
https://sockslist.net/check

优点是速度快, 稳定, 物理距离更远也无所谓.
缺点是测速不可靠, 所以需要自己尝试, 凭经验感觉. 免费节点其实很有限.

优质袜子代理同样是付费的
http://dichvusocks.us/tools.php
http://vn5socks.net/

◇ Http/ssl 筷子代理
ssl前置自动搜寻更新
http://www.sslproxies24.top/
http://www.gatherproxy.com/
http://proxysearcher.sourceforge.net/Proxy%20List.php?type=http

便捷检测
http://urlchecker.org/?proxy

优点是多多益善, 测速可靠工具多, 但是免费高速稳定的节点很少, 同样需要经验.

◇ 本机工具
1. Gather Proxy 收集出色[测试不佳]
http://www.gatherproxy.com/proxychecker

2. Socks Proxy Checker / SPC
https://www.socksproxychecker.com/

3. Elite Proxy Switcher /EPS
https://www.eliteproxyswitcher.com/

◇外卖管理机构
1. 美团
Proxifier
https://www.proxifier.com/download.htm
并不是越新版越好, 尽量选用稳定的旧版.

2.百度
ProxyCap
http://www.proxycap.com/download.html
破解容易反弹, 需要确保防火墙/hosts屏蔽

3.饿么
SocksCap64
https://sourceforge.net/projects/sockscap64/files/
https://www.sockscap64.com/homepage/
这个可以支持使用纸飞机做前置

-------------------------------------------------------

◆◆◆中国墙民外卖点餐名录
1. 纸飞机 Shadowsocks轻装 ShadowsocksR重甲
https://github.com/shadowsocks/shadowsocks-windows/releases
https://github.com/littleguyy/shadowsocksr_233
外卖时代, 再去攀比两者优劣, 毫无意义

2. 黄狗 GoProxy/Prom
https://github.com/out0fmemory/Goproxy-Always-Available/releases
out0fmemory 传奇ip施粥哥, 改版Goproxy, 自动扫描可用于Quic的ip.

Prom 社长羽化前临别赠礼
https://github.com/goproxy0/prom-releases

黄狗海洛因
https://cloudfra.com/xx-gp-v6.html

3 . 赛风 Psiphon
https://www.psiphon3.com/zh/download.html

基友
Klephon 印尼改版, 连接旧节点, 还有优势.
https://sourceforge.net/projects/klephon/

赛风可卡因
https://cloudfra.com/3proxy-psiphon.html

4. SSH
节点
印尼最新白金免费SSH, 之前分享过, 自行搜寻

Bitvise SSH Client
https://www.bitvise.com/ssh-client-download

基友
Putty/Myentunnel
https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html
https://github.com/feralhosting/feralfilehosting/tree/master/Feral%20Wiki/SSH/SSH%20tunnels%20-%20MyEnTunnel
ssh服务器支持Bvssh/putty不同, 最好同备. 有些节点Bvssh表现平平, 但putty就饱满.

6. 洋葱 Tor Browser
https://www.torproject.org/projects/torbrowser.html.en
外卖保证速度与稳定, 洋葱对袜4的支持一直都更好. 节点同时支持Socks4/Socks5, 选袜4.

7. 无名 JonDo
https://anon.inf.tu-dresden.de/win/download_en.html
现在是4个免费服务器, 限速100kb. 国内只能用socks5前置.

8. 狗蛋 GoGo tunnel
http://www.gogotunnel.com/
https://gitter.im/gogotunnel/gogo
整合外卖哥的先驱, 目前需要自建apps, 或者自行搜寻SNI代理

9/10. Ultrasurf + Freegate
http://ultrasurf.us/index.html

基友 Freegate
http://dit-inc.us/freegate.html
Freegate只能用部分亚洲前置, 像俄国或欧洲的, 这厮就要"肥水不留外人田"了.

外卖点餐, 还是儿时的味道.

11. 蓝灯 lantern
https://cloudfra.com/lantern-2010-new.html
该外卖喇~~

12. 东洋美鲍 SoftEther VPN
https://www.softether.org/
http://jp.softether-download.com/files/softether/

VPN Gate
http://www.vpngate.net/en

邮件订阅节点
http://www.vpngate.net/en/mail.aspx

早鸟们可以定向搜寻印尼或俄国, 他们也有提供免费节点.

13. 斯特拉 Stunnel
https://www.stunnel.org/downloads.html

节点来自李大师
本组, 自行搜寻

14. 绿凤凰 Simurgh
https://docs.google.com/file/d/0B2lH3w7DOYknRjJZMkVadVRtLVE/edit?usp=sharing
这是干净无投毒版本, 每天约1/3可用 -伊朗夜间

15. 洋葱代理 ChrisPC Anonymous Proxy
http://proxy.chris-pc.com/
需要外卖

◎◎VPS 方案
社长钦点 ipsec VPN(psk 模式)
https://github.com/hwdsl2/docker-ipsec-vpn-server

FuguHub MxTunnel 梭鱼
http://fuguhub.com/
全套VPS方案, 附带一个https代理做玩具

突厥 史翠珊 Streisand
https://github.com/jlund/streisand
自动化安装脚本, 同时生成客户端配置文件.
L2TP/IPsec, OpenConnect, OpenSSH, OpenVPN, Shadowsocks, sslh, Stunnel, a Tor bridge, and WireGuard.

**Comment by blob2015** [comment]
感谢J哥一而再、再而三……科普

**Comment by tec1987** [comment]
感谢J哥推荐的精品套餐。

**Comment by wegood9** [comment]
感谢J哥持续更新

tec1987 <notifications@github.com> 于2018年12月29日周六 下午5:47写道：

**Comment by fredericky123** [comment]
感谢J哥精品套餐

**Comment by xugaohui** [comment]
第一个链接,大多不可以用.原因是很多都是国内的代理.本身被墙了.
Gather Proxy 9.5 这个检查代理还是十分准确的
至于在线检测代理这些都没用处.它是检测的网页服务器到代理之间的连接.不是本机的连接环境.
 SoftEther VPN这几天只有连接几分钟就断开了.试了很多次都一样.准备试试OpenVPN

**Comment by hcym** [comment]
openvpn几乎没有速度，我是完全搬瓦工，手机用ss或者wireguard，pc直接v2ray，正常基本4k，白天8k也凑合看
