### ISSUE TITLE
新玩具 Mysterium Network

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#187]
https://mysterium.network/
Mysterium Network is a fast and scalable transport security layer. Our mission is to build a P2P decentralised network using multi-hops, relays and an inbuilt micropayments tokenomic model.

dl: https://mysterium.network/vpn/download-alpha/

同样也是匿名为主的VPN~~

**Comment by blob2015** [comment]
感谢J哥

**Comment by tec1987** [comment]
匿名为主的VPN，就不要要求速度了。。。

**Comment by xugaohui** [comment]
![fdfdfdfd](https://user-images.githubusercontent.com/18757174/50582581-8d509180-0e9e-11e9-9930-e11efcf4ccd9.png)
实测图
