### ISSUE TITLE
新玩具 Invisible Man

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#191]
Invisible Man
https://invisiblemanvpn.github.io/

Changelog
https://github.com/InvisibleManVPN/InvisibleMan-VPNClient/releases

Free PPTP VPN

**Comment by tec1987** [comment]
下载试试，多谢J哥

**Comment by fredericky123** [comment]
连了几个节点 都连不上去 而且还不能自动选节点 诸多功能还不完善
