### ISSUE TITLE
新枪械 Mysterium Network

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#192]
https://mysterium.network/
https://github.com/mysteriumnetwork/mysterium-vpn

区块链VPN公益项目

Intro
https://blockchainreporter.net/2019/01/22/interview-with-mysterium-founder-robertas-visinskis/

**Comment by hubsocks** [comment]
mysterium-vpn备用还可以.速度如图
![2222222](https://user-images.githubusercontent.com/46856823/55312409-0ceafe00-5498-11e9-9582-37bd05dc5e71.png)

比xx net差.
Invisible Man都连不上.

**Comment by jasonliul** [comment]
https://www.nirsoft.net/utils/serviwin.html
用这个尼尔工具， 改为手动启动～

**Comment by jasonliul** [comment]
@hubsocks
https://www.nirsoft.net/utils/serviwin.html
用这个尼尔工具， 改为手动启动～

http://i63.tinypic.com/33lh5wz.jpg

**Comment by jasonliul** [comment]
https://a.radikal.ru/a07/1904/29/771d5376b580.jpg
@hubsocks
https://www.nirsoft.net/utils/serviwin.html
用这个尼尔工具， 改为手动启动～

**Comment by jasonliul** [comment]
v 0.80/0.81
Service provider mode introduced
Service provider fixes
Service can whitelist consumers he wants to release

**Comment by hubsocks** [comment]
0.80很早就出来了，作者发布几天后就删掉了。今天试了下0.81,先绿化它。但节点列表还是无法刷新，再等下一个版本了。应该是被封了。xxnet+ipv4继续完美使用中。

**Comment by jasonliul** [comment]
0.94
