### ISSUE TITLE
洋度盘～～～

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#193]
可以离线下载， 反倒强过百毒 --下载不限速。

介绍机制比较有趣， 双方都会多500M...

俺的推介链
https://www.seedr.cc/?r=2562276

**Comment by jasonliul** [comment]
另一个
https://zbigz.com/

**Comment by blob2015** [comment]
现在都不怎么敢存东西到网盘了

**Comment by jasonliul** [comment]
@blob2015
百度的离线下载是假的, 只是等发种子的凯子, 回头上传度盘.
有些在中国的外国友确认过...

这两个才是真正离线下载bt, 而且并没有被封杀. Seedr下载没有限速, 用IDM就行

**Comment by blob2015** [comment]
感谢J哥解答

**Comment by jasonliul** [comment]
天天, 人人都被扁,
这下有用了

**Comment by jasonliul** [comment]
https://www.torrentsafe.com/
这个不用注册, 文件不能大于1G
