### ISSUE TITLE
还存活的雕~~

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#195]
https://darrenliuwei.com/%E5%85%8D%E8%B4%B9ss%EF%BC%8Cssr%EF%BC%8Cvpn%EF%BC%8Cbrook%E8%B4%A6%E5%8F%B7%E5%AF%86%E7%A0%81%E5%88%86%E4%BA%ABfree%EF%BC%8Cssr%EF%BC%8Css%EF%BC%8Cvpn%EF%BC%8Cbrook%EF%BC%8C%E5%85%8D%E8%B4%B9%E7%BF%BB%E5%A2%99.html

需要这个
https://ocr.space/

**Comment by jap33** [comment]
唉！就你一个人。

**Comment by jasonliul** [comment]
@jap33
海少, 出来接客喇~~~

**Comment by SeaHOH** [comment]
:eyes: 叫我？ :eyes:
其实这种分享多得很，搜索一下很容易找到（当然你不能用百毒），就是站点本身容易被封，也许用图片分享的能坚持得久点？

**Comment by blob2015** [comment]
大海兄还是在的，再怎么着

**Comment by jasonliul** [comment]
海少还在, 俺就安心去睡了~~
:)

**Comment by jasonliul** [comment]
@jap33
谷阔佬关闭G+, 你不去卖雕了?
