### ISSUE TITLE
可怜的旧雕, 死翘翘

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#196]
https://github.com/shadowsocks/shadowsocks-windows/issues/2244#issuecomment-468142181

SS居然要玩插件了, 太复杂~~~

**Comment by tec1987** [comment]
早就有了吧。。。

**Comment by blob2015** [comment]
俺就先等着，反正再不济，用镜像先，yt什么的，对俺来说是可有可无的

**Comment by NAVrasZ** [comment]
混淆流量一大照样被限速，只是不封

**Comment by jasonliul** [comment]
@NAVrasZ
现在夜间都会明显被拖慢~~

**Comment by NAVrasZ** [comment]
同样... 拖延办法有放一天不用，勤换ip (发现我等被限速再换，换的ip也被一起限速...)，混淆勤换域名。都相当麻烦...

**Comment by pgz123** [comment]
哎

**Comment by jasonliul** [comment]
@NAVrasZ
俺不能理解国人包不同的偏执.

其实可以把自家节点做成带密码的透明socks5节点, 
然后各路免费纸雕尽情享用~~
