### ISSUE TITLE
伟大的俄罗斯防火墙开造~~

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#198]
俄罗斯杜马以压倒性的多数通过允许俄罗斯创建自主互联网的法案。新法将为“俄网（Runet）”创建一个独立的基础设施，让俄罗斯在遭遇攻击时拉起“虚拟吊桥”

总理带头的官员一再强调并非中国网络长城.

令俺吃惊的是业界也认同这一点, 看起来俄国并非俺们的网络病友.

俄国业界人士的观点
Техническое отключение страны от глобального интернета возможно, такие примеры в мире есть — речь о проекте «Золотой щит» в КНР, который чаще называют великим китайским файерволом. Политически такое решение принять тоже могут, и вряд ли что-то сможет этому помешать, но вопрос — решатся ли на этот шаг.

    Отделение от глобального интернета неизбежно повлияет на имидж страны и может повлечь за собой ухудшение инвестиционного климата. Информационная изоляция может привести к технологическому отставанию, как это было в случае с советским железным занавесом.

**Comment by hcym** [comment]
无所谓，该翻就翻会飞的还是飞越疯人院

**Comment by tec1987** [comment]
此墙非彼墙。。。。

**Comment by immeman** [comment]
虽然说是应急措施，但我总觉得是温水煮青蛙

**Comment by jasonliul** [comment]
幌子是预防大规模网战, 但有这能力的只有美国中国, 北极熊惹不得~
