### ISSUE TITLE
海少玩具: GreenTunnel v1.3.2

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#199]
GreenTunnel v1.3.2
https://github.com/SadeghHayeri/GreenTunnel/releases/tag/v1.3.2

**Comment by SeaHOH** [comment]
其实我没玩过，不知为何总觉得 Node 很 :fearful: ，基本不碰。

**Comment by jasonliul** [comment]
@SeaHOH
其实Fxxx得动长城~~~
波斯玩具很少这么强悍

**Comment by SeaHOH** [comment]
> 其实Fxxx得动长城~~~

是的，看过源码，居然是用的分割数据包的手段，之前我试过是不起作用的，看来只是具体方法没有搞对。

**Comment by blob2015** [comment]
@SeaHOH 
大海兄又接了一招 :)

**Comment by SeaHOH** [comment]
> > 其实Fxxx得动长城~~~
> 
> 是的，看过源码，居然是用的分割数据包的手段，之前我试过是不起作用的，看来只是具体方法没有搞对。

实际运行了 GT，在我这里没法避开 SNI 检测。
抓包查看，发现和我之前实验的包是一样的，都是 [PSH, ACK] 。

**Comment by tec1987** [comment]
有空去试试这个：
https://github.com/ValdikSS/GoodbyeDPI

**Comment by SeaHOH** [comment]
这个靠谱，是直接丢弃虚假 RST。

**Comment by tec1987** [comment]
哈哈

想搭个youtube梯子
https://you2php.github.io/
各位有没有免费主机能推荐一下的？

**Comment by jasonliul** [comment]
Free VPS, DIY 必备 #176

**Comment by jasonliul** [comment]
俄国这个是命令行的

**Comment by tec1987** [comment]
谢谢J哥
