### ISSUE TITLE
欧洲部分媒体, 机译党

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#202]
EU
http://www.eubusiness.com/
http://www.euobserver.com/
http://www.euractiv.com/en
http://www.euronews.net/
http://europetodayonline.com/
http://eux.tv/
http://www.presseurop.eu/
http://www.theparliament.com/
http://www.worldcrunch.com/
http://www.europeanvoice.com/
http://www.rferl.org/default.aspx

FR
http://www.lesechos.fr/
http://www.lemonde.fr/
http://www.france24.com/
http://lci.tf1.fr/
http://info.france2.fr/

DE
http://www.tageschau.de/
http://www.handelsblatt.com/
http://www.sueddeutsche.de/
http://www.bild.de/
http://www.dw-world.de/
http://www.heute.de/
http://www.spiegel.de/
http://www.faz.net/
http://www.fr-online.de/

GB
http://www.bbc.co.uk/news
http://news.sky.com/skynews/
http://www.telegraph.co.uk/
http://www.guardian.co.uk/

ES
http://www.abc.es/
http://www.elmundo.es/
http://www.elpais.com/
http://www.antena3.com/noticias/
http://www.telecinco.es/informativos/

PT
http://www.tvi24.iol.pt/
http://www.publico.pt/
http://sic.sapo.pt/online/homepage
http://www0.rtp.pt/homepage/
http://economico.sapo.pt/

IT
http://www.lastampa.it/
http://www.repubblica.it/
http://tg24.sky.it/tg24/
http://www.ansa.it/

Ru
http://gazeta-pravda.ru/
https://www.kommersant.ru/
http://tass.com/
http://www.aif.ru/
https://ria.ru/
http://www.russiaprofile.org/
https://sputniknews.com/

etc
http://www.swissinfo.ch/
http://www.svd.se/
http://www.hs.fi/english/
http://www.thenews.pl/
http://www.rtbf.be/info/
http://www.lesoir.be/
http://praguemonitor.com/
http://www.ceskenoviny.cz/news/
http://www.rte.ie/news/
http://www.irishtimes.com/
http://www.portfolio.hu/en/
http://www.hurriyetdailynews.com/
http://www.ekathimerini.com/
https://www.b92.net/eng/
http://www.eurasianet.org/
http://www.caucaz.com/home_eng/

华文欧美媒体, 近来完全变味, 简直是华语泼妇骂街集中营...
还不如机译阅读, 与列国草根哈拉有趣~~

**Comment by 2378** [comment]
真受不了了，我也想做点传播啊，想了很久了，几个隔壁的路由我都破解了，可通过网络总觉得不安全

大家别笑，我想过最土的办法，搞点廉价光盘、U盘，偷偷丢到城市各个角落，又怕朝阳大妈发现

这次讲这些，算是最大胆一次了

**Comment by jasonliul** [comment]
俄国的所谓中文网实在太扯淡.

搜索 Теги: торговая война, китай, сша 去看看, 爱面子的中国, 从来不是爱里子的俄国对手.
实际上俄国, 日本超级了解中国, 反过来中国对他们一无所知.

中俄从来不是盟友, 仅仅是伙伴.
Тем не менее у «дружбы» Си и Путина есть свои пределы, и ее точно нельзя назвать «альянсом», как твердят китайские власти. «У России нейтральный подход к конфликту в Южно-Китайском море. Китай в свою очередь не делает прямых заявлений по поводу Крыма и развивает отношения с Киевом в соответствии с собственными интересами. Обе страны могут предложить друг другу моральную поддержку, но не в состоянии наладить операционное сотрудничество в военной сфере. Такой поворот был бы невыгодным для Москвы, поскольку она заинтересована в развитии энергетического и военно-технического сотрудничества не только с Китаем, но и с другими странами Азиатско-Тихоокеанского региона, а также с ЕС», — отмечает эксперт.
