### ISSUE TITLE
兼聽則明...

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#203]
https://t.co/sEapoGNdlg
https://t.co/rGpn14jBUt
https://t.co/RAGyXpxqtp

致謝翻譯達人

**Comment by SeaHOH** [comment]
老美反射弧太长。。。

**Comment by jasonliul** [comment]
https://www.youtube.com/watch?v=SvJKZuv3Lqs
兩女掐架, 看沒?

**Comment by SeaHOH** [comment]
国际精英打脸美国女孩，格局决定结果。
就这样，我朝也没有详细报道，心里门儿清，嘴强罢。

**Comment by jasonliul** [comment]
天朝嘴炮, 從來都是贏.
LOL

**Comment by xugaohui** [comment]
就因为这事导致哀雕遍野, 好惨.结果千万不能让你们知道.
