### ISSUE TITLE
秋水逸冰大大也著草去咧~~

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#209]
秋水逸冰大大也著草去咧~~
https://teddysun.com/548.html

**Comment by SeaHOH** [comment]
人作为智慧生命，失去了一些本能，甚至还诞生了反生存的要素。

“身体是革命的本钱。”，这句话挺有道理的。
人能够学习知识，所以，要时刻记得保护自己，就这么个简单的道理。
