### ISSUE TITLE
使用linux和ubuntu系统搜索不出IP来

### ISSUE THREAD

**Issue by hcym** [Kisesy/gscan_quic#4]
还是不能，老版本也是一样，只能扫描一行
$ cd /tmp/gscan_quic && ./gscan_quic_linux_amd64 
2017/07/15 23:03:29 Start loading IP Range file:./iprange.conf
2017/07/15 23:03:29 Start scanning available IP
2017/07/15 23:03:29 Scanned 1000 IPs, Found 0 records
2017/07/15 23:03:29 Scanned 2001 IPs, Found 0 records
2017/07/15 23:03:29 Scanned 3000 IPs, Found 0 records
2017/07/15 23:03:29 Scanned 3056 IPs, Found 0 records
2017/07/15 23:03:29 Scanned 4000 IPs, Found 0 records
2017/07/15 23:03:29 Scanned 5001 IPs, Found 0 records
2017/07/15 23:03:29 Scanned 6000 IPs, Found 0 records
2017/07/15 23:03:29 Scanned 7000 IPs, Found 0 records
2017/07/15 23:03:29 Scanned 8000 IPs, Found 0 records
2017/07/15 23:03:29 Done
2017/07/15 23:03:29 Scanned 8448 IP in 0.026227s, found 0 records
2017/07/15 23:03:29 All results writed to /tmp/gscan_quic/google_ip.txt

**Comment by Kisesy** [comment]
哦，从来都不行？

你先把这些IP添到 Goproxy 里试试能不能用


	"108.177.97.153","113.171.216.137","113.171.216.23","113.171.216.150","113.171.216.16","113.171.216.132","113.171.216.138",
	"113.171.216.6","113.171.216.144","113.171.216.140","113.171.202.46","113.171.216.123","113.171.216.136","113.171.216.148",
	"113.171.216.126","113.171.216.87","113.171.216.105","113.171.216.141","113.171.216.92","113.171.216.103","113.171.216.95",
	"113.171.216.51","113.171.216.83","113.171.216.21","113.171.216.119","113.171.202.56","113.171.216.118","113.171.216.18",
	"113.171.216.17","113.171.216.115","113.171.216.135","113.171.202.27","113.171.216.100","113.171.216.107","113.171.216.111",
	"113.171.216.35","113.171.216.143","113.171.216.81","113.171.216.78","113.171.216.86","113.171.216.27","113.171.216.85",
	"113.171.202.21","113.171.216.74","113.171.216.34","113.171.216.39","113.171.216.108","113.171.216.29","113.171.216.84",
	"113.171.216.4","113.171.216.9","113.171.216.58","113.171.216.139","113.171.216.82","113.171.216.145","113.171.216.104",
	"113.171.216.57","113.171.216.98","113.171.216.110","113.171.216.88","113.171.216.20","113.171.216.50","113.171.216.32",
	"113.171.216.19","113.171.216.28","113.171.202.44","113.171.216.11","113.171.216.33","113.171.202.19","113.171.216.12",
	"113.171.216.77","113.171.216.13","113.171.216.109","113.171.216.52","113.171.216.142","113.171.216.40","113.171.202.29",
	"113.171.216.25","113.171.202.22","113.171.216.106","113.171.202.26","113.171.216.36","113.171.216.75","113.171.216.101",
	"113.171.216.151","113.171.216.73","113.171.202.15","113.171.216.42","113.171.202.30","108.177.97.120","113.171.216.120",
	"113.171.216.62","113.171.216.89","113.171.216.38","113.171.202.5","113.171.216.30","113.171.216.121","113.171.202.41",
	"113.171.216.94","113.171.216.69","113.171.202.47","113.171.216.76","113.171.216.41","113.171.202.54","108.177.97.155",
	"113.171.202.39","113.171.216.153","113.171.202.10","113.171.202.23","113.171.202.6","113.171.216.31","108.177.97.112",
	"108.177.97.196","108.177.97.84","113.171.216.43","108.177.97.137","113.171.216.96","108.177.97.200","108.177.97.116",
	"113.171.216.99","113.171.216.102","108.177.97.161","113.171.216.154","113.171.216.48","113.171.202.42","113.171.216.46",
	"113.171.216.91","113.171.216.5","113.171.216.93","113.171.216.79","113.171.216.146","108.177.97.152","113.171.216.134",
	"113.171.216.113","113.171.216.97","113.171.202.34","113.171.202.52","113.171.216.133","113.171.216.152","113.171.202.8",
	"113.171.216.149","108.177.97.83","113.171.202.32","113.171.202.50","108.177.97.146","113.171.216.117","113.171.216.116",
	"113.171.216.44","113.171.216.122","113.171.216.15","113.171.202.59","113.171.202.48","113.171.216.80","108.177.97.151",
	"113.171.216.22","113.171.216.24","113.171.202.58","108.177.97.119","113.171.202.17","113.171.202.38","113.171.202.49",
	"113.171.216.45","108.177.97.107","113.171.202.12","113.171.216.26","113.171.216.10","113.171.202.25","113.171.216.90",
	"113.171.216.72","113.171.202.62","113.171.202.31","113.171.216.70","113.171.216.37","113.171.202.11","113.171.202.7",
	"113.171.202.35","108.177.97.136","113.171.202.33","113.171.202.16","113.171.216.68",

**Comment by hcym** [comment]
好的。谢谢

**Comment by hcym** [comment]
能用的，主任果然有货，感觉比我的快一点
下午我还用一行一个填IP
也是只扫第一行就停止，网页编译的也是
ubuntu系统1604和1704一样的情况

**Comment by MeABc** [comment]
编码？换行符没处理？猜测

**Comment by Kisesy** [comment]
能用quic ip，却不能扫，嘿嘿，不好弄了
下载 https://gox.jpillora.com/ 最新版，里面 1.1的那个试试

**Comment by hcym** [comment]
编码换行
回头我再用自己的ip段文件试试看，这个可能性大

**Comment by Kisesy** [comment]
@hcym 试试最新版吧

**Comment by hcym** [comment]
刚刚下载，等空调降温再试试看
有没有amd64环境正常使用的哥们？
因为我的是最小安装的lubuntu
经常有些莫名其妙的事情

**Comment by hcym** [comment]
$ cd /tmp/gscan_quic && ./gscan_quic_linux_amd64 
2017/07/16 10:10:54 Start loading IP Range file:./iprange.conf
2017/07/16 10:10:54 Start scanning available IP
2017/07/16 10:10:54 Done
2017/07/16 10:10:54 Scanned 512 IP in 0.002633s, found 0 records
2017/07/16 10:10:54 All results writed to /tmp/gscan_quic/google_ip.txt
还是只扫一个，换过IP格式也是一样
暂时不管吧，看看有没有linux正常运行的

**Comment by Kisesy** [comment]
你这不是扫一行
上楼 Scanned 512 IP in 0.002633s, found 0 records  这里扫了两个段
一楼 2017/07/15 23:03:29 Scanned 8448 IP in 0.026227s, found 0 records 这里扫了30多个段
其实就是扫不出IP来
你这估计跟 #3 的是一样的问题，以前的时候社长也说过有的网络禁用 udp，https://github.com/Kisesy/gscan_quic/issues/3#issuecomment-315544558 也说到这个

**Comment by hcym** [comment]
哦，明白了
我是在光猫上封了 udp和samba
呱呱呱

**Comment by THLIVSQAZ** [comment]
这就不像网络问题了吧。。。。。。#3
![screenshot from 2017-07-16 07-53-54](https://user-images.githubusercontent.com/25531652/28245830-b3c8827a-69d4-11e7-99da-ba598ae1e743.png)
![screenshot from 2017-07-16 07-53-31](https://user-images.githubusercontent.com/25531652/28245826-a9b1ba72-69d4-11e7-83b2-9c83a6af0fa3.png)

**Comment by Kisesy** [comment]
是有这个问题，我看看

**Comment by hcym** [comment]
没天理啊
xp_32可以，win7_64和ubu都不行
我还是把光猫恢复吧

**Comment by Kisesy** [comment]
我发现问题了，实际上不是代码的问题，而是 quic-go 使用 udp 访问 ip 的时候出现了一个错误
2017/07/16 11:51:07 write udp [::]:41730->203.248.132.241:443: sendto: operation not permitted
这个错误你们可以搜索 sendto: operation not permitted ，看看怎么解决，比如 http://blog.csdn.net/lucky_greenegg/article/details/43192333
我不用这类系统，我也没办法

**Comment by hcym** [comment]
ok
先用xp吧，

**Comment by Kisesy** [comment]
@hcym 
顺便说下，这种错误是在高并发下产生的，只要在 gscan.conf  里把 VerifyPing 改成 "VerifyPing":  false, 
然后把并发调低，比如调成 5，就可以扫IP了，虽然比较慢

**Comment by hcym** [comment]
啊
好的，100那个是不是并发
xp扫的太快了

**Comment by Kisesy** [comment]
@hcym 嗯，就是扫的很慢
![image](https://user-images.githubusercontent.com/5843694/28247572-8a8df00c-6a65-11e7-9457-b5ad34845de2.png)

**Comment by hcym** [comment]
5，10，50到可以
50足够快了
谢谢谢谢

**Comment by qwerttaa** [comment]
昨天试了半分钟，开到1500，路由器没看，反正cpu占用了40%

**Comment by hcym** [comment]
谢谢主任，能不能去掉这个issues
  gscan.conf 里把 VerifyPing 改成 "VerifyPing": false
就ok了，quic的IP取之不尽用之不竭啊啊吖
