### ISSUE TITLE
有趣的新玩具 ReQrypt

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#42]
ReQrypt
https://reqrypt.org/reqrypt.html

ReQrypt - Extra tunnels

Copy and paste any of these URLs into the TUNNELS tab:

    ping://191.101.180.77:40404?crypt=cipher.aes,cert.3=j3L53U9Jy0jhMsyaUmDe,sec.2888
    (tunnel traffic via ping packets).
    udp://191.101.180.77:12345
    (tunnel with no encryption).

[U][B]ReQrypt 1.3.1 x64[/B][/U]
[url]https://github.com/basil00/reqrypt/releases/download/v1.3.1/reqrypt-1.3.1-win64-install.exe[/url]

Portable
[url]https://github.com/basil00/reqrypt/releases/download/v1.3.1/reqrypt-1.3.1-win64-files.zip[/url]

巴西翻墙玩具, 声明不能直接捅gfw, 不过现在不是直捅早泄的时代了...

看起来这个玩具像ssh的动态压缩, 因此会有加速的作用, 如果能够搞成前置使用, 也蛮符合国情, 现在ssh, 甚至纸机都有被人为拖慢的问题.

好事者尝鲜去罢~~~
:)

**Comment by tec1987** [comment]
等技术大神来搞

**Comment by jasonliul** [comment]
新版意外的在俄国得到关注...
欧洲通常都是超薄护垫式的墙~~~

巴西人纠集西葡语人士, 满世界测试...
这个真是赞!! 远比中国人有国际视野

**Comment by qwertccc** [comment]
似乎不nb的样子
