### ISSUE TITLE
再推推原来的梭鱼 4.8 2018/01

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#43]
**梭鱼, SS的龙凤胎**

同属支持商用加密的免费高匿名代理, 不过代理类型是http.

现在梭鱼是全套私人VPS方案, 不只是代理.

既然自掏腰包, 国人不应苟且仅图翻墙, 期待教程达人作出傻瓜画瓢文~~

Changes for 7.4   September 2016
 ---------------------------------
 * Updating ChaCha20 and Poly1305 to rfc7539

FuguHub – 免费的Web服务器供个人使用。

发行内容：
 - 用户手册，对所有配置和调试操作进行逐步描述;
 - 文件管理器，允许您从任何其他计算机的浏览器远程管理服务器上的文件;
 -  WebDAV，一个先进的文件管理器，它也允许你查看整个服务器的本地磁盘;
 -  HTTPS隧道，访问隐藏和安全的服务，例如电子邮件;
 - 一个Web服务器，允许您组织简单的主页的工作，以及更复杂的网站与数据库和应用程序;
 - 具有特权系统的多用户访问;
 - 服务器和聊天客户端，用于管理员之间的通信;
 - 许多功能的编辑;
 - 游戏，现成的脚本例子等

主页
http://fuguhub.com/

**Comment by jasonliul** [comment]
Changes for 7.8 January 2018
---------------------------------
* Updating FuguHub to latest Barracuda App Server library.
This release deprecates and removes several APIs such as the EventHandler.

Changes for 7.6 March 2017
---------------------------------
* Adding SNI support

Changes for 7.5 October 2016
---------------------------------
* Product name changed from BarracudaDrive to FuguHub

越来越适合反审查...

**Comment by Asteroids89** [comment]
https://bbs.kafan.cn/thread-1834651-1-1.html 
 J大，你还做浏览器呀，NB

**Comment by wegood9** [comment]
诶，J哥的卡饭账号不是被封了吗，还能编辑帖子？
