### ISSUE TITLE
新玩具 QTGate

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#47]
QTGATE是一种安全通讯手段，通过eMail的IMAP协议建立一个虚拟的专用通道，连接客户端和代理服务器，它的奇妙之处在于客户端和服务器彼此不用知道相互的IP地址，而是通过共用一个eMail账号进行数据交换，QTGATE系统把VPN包加密后，利用IMAP进行通讯，能最大限度的保护您的网络通讯不被检测和干扰，建立一个私密的网络安全环境。 QTGATE提供本地Proxy服務器對應HTTP, HTTPS, SOCKS 4,4a,5。其他設備可以通過設置proxy來使用QTGate.

https://github.com/QTGate/QTGate-Desktop-Client

免费使用仅仅100M/D, 1G/M, 因此有VPS的话, 不如自己搭建~~

**Comment by 2378** [comment]
mark

**Comment by QTGate** [comment]
嗯，自己搭建可否每2小時能夠變化代理服務器的IP地址？能否同時使用多條代理服務器，來降低大流量集中在同一IP上引起監控者的注意？能否使用iOPN和@OPN技術？
iOPN是客戶端和代理端的通訊使用HTTP協議混淆技術，它是短連結，和打開一個普通網站的一個動作完全一樣，每次request或post都關閉連結。
@OPN是客戶端和代理端使用IMAP協議混淆技術，利用公眾email服務器來進行數據交換，在不需要知道彼此IP地址的前提下進行VPN通訊，除非牆把Yahoo郵箱，Apple郵箱，outlook郵箱屏蔽，否則無法堵住通訊。

**Comment by jasonliul** [comment]
@QtGate
居然直接钓到大大真身~~~
列位, 快来揪住索取利好.
:)

**Comment by QTGate** [comment]
剛才Google了一下QTGate關鍵字。發現竟然閣下對QTGate有怨言，不撫平您不行啊。

**Comment by QTGate** [comment]
有在國內生活的各位，願意每週做一次測速報告，可來信告知，我這裡有少量$6.88測試帳戶（每月限流量300GB，無日限流量）的一年訂閱可以奉上，請email: info@QTGate.com，麻煩註明在中國哪個城市。謝謝各位。

**Comment by jasonliul** [comment]
@QTGate
这个玩意, 俺已经推介俄圈用户, 大大留一点广告费, 也是应该~~
哈哈...

没有怨言那得流行? 
天朝已经琼瑶化了.......... :)

**Comment by QTGate** [comment]
感謝您。我們還在開發使用OPN技術的另外二個應用：QTChat類似推特的匿名信息推送系統，可直接推送信息到客戶端，支持文字圖片和視頻（免費），和QTStorage匿名隱密雲文件存儲和分享系統（免費）。和隱身代理服務器上網合併在一起，號稱2018年網絡匿名三劍客。

**Comment by e2889e** [comment]
- 封邮箱地址比封ip容易多了
- 查邮件来源比查ip容易多了
- 监控邮箱比监控ip容易多了

**Comment by QTGate** [comment]
QTGate匿名網絡使用IMAP協議來連結各個QTGate客戶端，非SMTP協議。

監控者通過加密通道側信息洩漏，檢查這個IMAP加密通訊看看正在使用哪個郵箱那是不可能的。

QTGate的匿名網絡只對應牆外的6個郵箱，Outlook，Apple，Yahoo，Gmail，GMX，ZOHO。

所以監控者如果要檢查郵箱，需要解密以上郵箱的IMAP通訊，才能夠獲得郵箱信息。

**Comment by e2889e** [comment]
国内服务器都是他们的,要这么监控吗?
国外大不了就是"封",例如gmail.

**Comment by QTGate** [comment]
對，我正等著他們把Apple，outlook等大牌郵箱全部封掉呢。

**Comment by jasonliul** [comment]
@QTGate @e2889e
大大客气了...这款工具本身是中国墙民最需要的, 新鲜, 强势, 亲民, 中国范~~ 中国墙民对于国际反审查工具, 始终有一种隔膜, 不能融入国际墙民大家庭.

俺相当惊奇大大亲自现身, 力挽狂澜.

这次的封杀, 本身中国墙工已经国际接轨, 成为网络贸易壁垒的榜样, 实际上他们不大可能再做任何粗暴封杀, 因为在因特网对接中, 会招致对等报复.

何况去年网络大款们, 已经煽动过"维护互联网中立性"活动, 表明过自身的利益关切. 而且中国, 俄国意外地表态不会得罪这些金钱巨鳄.

可悲的是, 中国墙民依然活在圈圈, 鸽子时代的伪政治论调里面. 

俺留意到两点, 波斯的新工具Fshekan, 来自原绿凤凰团队, 这个工具已经去政治化, 开始与国际接轨. 不再一根筋侈谈人权民主.

土耳其Joshua Lund的立场, 代表自2015年以来,墙国/墙民各自结盟以后的新世纪, Joshua 的表述去掉宗教, 政治, 或其他差异因素, "墙民是弱者, 但我们会以牙还牙, 少说废话", 这是普世情感. 也是现在大家公认的国际墙民的立场.

SS/SSR已经混入许多官商, 那些所谓审计 --审查的美称, 也就是"一边审计, 一边创收", 纸飞机的公信力大打折扣, 也连带一些其他工具, 例如gogo... 完全理解, 无法接受.

俄国入伙墙国以后, 地球大半都是墙国, 而且核心是金钱. 官商卖VPN, 等于二次销售网络服务, 核心不是政治... 那些大话民主的屁书生可以关门手淫去了.

大家都在观望QTGate的作为, 如果你们也加入所谓审计的话....LOL

恭喜发财!!! 最特色的中国式问候~~
大大们努力赚钱, 墙民们努力捅墙, 双赢新局面.

**Comment by QTGate** [comment]
我們公司確實是一個追求盈利的公司，但如果在技術上能夠掙得金盆滿貫，何必需靠出賣靈魂換取利益呢？況且我們老闆是加拿大人，本來就厭惡言論審查，所以和我一拍即合，創辦了在追求利潤的同時，還可以堅定我們的言論自由信念的項目，這就是每個人生命的理想狀態。
反觀如今在全球和我們技術能夠競爭的對手不多，我們應該是站在這個行業的最前端。所以在藍金黃面前，我們有比藍金黃更廣闊的錢途，只有傻子會對眼前利益眼紅。
我們將來的競爭對手是FB推特，按他們的市值比照的話，應該拿出幾千億$來買我們這麼一個小公司。
我們老闆希望將來讓公司變成一個上市公司，成為大家離不開的生活必須的life line.由社會來監督運行。

**Comment by qwertccc** [comment]
@QTGate 想试一下，https://github.com/QTGate/QTGate-Desktop-Client/releases/download/v1.2.1/qtgate.Setup.1.2.1.exe 这个地址下载不了

**Comment by e2889e** [comment]
技术太一般了...
理论上完全不可能做大...
就是吹牛还行...

**Comment by QTGate** [comment]
麻煩您列舉一下目前在世界上有哪個VPN供應商：

- 可以提供同時使用多條代理服務線路，並聯使用的？
- 有哪個可以每2小時變換代理服務器地址的？
- 有哪個可以提供沒有指紋特質，不被牆發現而可以隱身出入牆體的？

**Comment by e2889e** [comment]
本人接触代理多年.
不提供免费的技术分析.

**Comment by QTGate** [comment]
那感謝您已經為QTGate進行了免費分析，認為QTGate做的以上的技術完全不值得一提。

**Comment by jasonliul** [comment]
@QTGate
秀才舌辩无意义.

中国袜子ss倒是有技术特色, 俄国, 菲律宾, 香港, 美国, 加拿大...都有一些VPN服务商拿来取代付费的ssh, 不过比较偏重移动端客户群. 而国内始终不过是集市排挡... 俺没有见过如此糟糕的商务运作.

用户关心的是商务问题, 例如团购打折, 代建托管... 这类问题.
还有天朝已经是摇奖红包纪元, 推荐朋友这类, 有木有摸奖送流量? 不在于多, 而在于乐~

比对印尼, 墙工墙民一家亲, 最得意的反倒是墙商, 既然人为造就巨大市场需求, 何如大家都得一杯羹? 印尼的墙商, 官家/草根都有, 那是成年人的双赢本能, 也是2016年以来全球最佳墙民~~

顽童村姑式舌辩不休, 逞能争胜的新物种, 只有中国人~~ 
成人世界的赢只有一种 --双赢,

**Comment by mixool** [comment]
免费账号测试链接了一下新加坡的服务器，油管1W+

**Comment by QTGate** [comment]
目前版本有一個問題是免費帳戶無預警的，不能夠打開網站，那是因為免費用戶流量已經用完，不過您還可以打開[維基百科](https://zh.wikipedia.org/wiki/Wikipedia:%E9%A6%96%E9%A1%B5)，[維基百科](https://zh.wikipedia.org/wiki/Wikipedia:%E9%A6%96%E9%A1%B5)網站是不計算流量的。在今後的版本中，我們會改善這一點，會給出提示頁面。還有您可以在連結上後，使用手機和平板電腦的Proxy連結到您這台安裝了QTGate客戶端的電腦上網。我們沒有可連結的台數限定。

**Comment by itnewgay** [comment]
感觉完全打不开啊
