### ISSUE TITLE
又一个中国特色的心照不宣~~

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#49]
很抱歉的告诉大家，由于硬盘坏掉所有的数据都丢失了。 SSTAP和SOCKSCAP64将永久停止开发。 11/18/2017

https://www.sockscap64.com/

又一个中国特色的心照不宣~~

**Comment by tec1987** [comment]
作为一个有经验的软件开发者，我就不信没有备份。。。

**Comment by jasonliul** [comment]
![screenshot 1](https://user-images.githubusercontent.com/2461165/33527252-73c9cbfc-d888-11e7-9af5-2052a50afb8f.jpg)

**Comment by blob2015** [comment]
定点清除，不是第一个，也不会是最后一个。
这也是国外很多社区与“独狼”不会遭遇的境况，超强的把控力。除此以外，再对某些行为睁一只眼闭一只眼，一颗屎坏一锅汤。
这就是奖惩的威力。
很多措施，不是说完全不好，甚至有必要，就是心太大，私心重，不管不顾，导致现实的结果，就是虽然好像那么做了也没啥严重后果，但日积月累，那天，搞不好就来一个大的，因为，总会急躁，耐心总会消耗殆尽，总会喝高。
当然啦，俺们也就小虾米，甚至小虾米也未必算得上，神仙打架，遭受余殃。
不过，这也算是教训吧，冷清下，也没啥不好。
