### ISSUE TITLE
居住中国的俄国达人翻墙搭建Nextcloud教程

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#53]
居住中国的俄国达人翻墙搭建Nextcloud教程, 之前作者也尝试过SS, Streisand
https://geektimes.ru/post/294997/

Nextcloud
https://nextcloud.com/
这种方式中国人好像没有试过~~

**Comment by wpyok500** [comment]
@jasonliul 推荐一些免费的fq软件吧，像之前的gp、gogo类的，这种vps目前国内主流还是ssr

**Comment by blob2015** [comment]
@wpyok500 
J哥一直有推荐，可惜，社长闭关当中，帖子暂时找不到罢了
