### ISSUE TITLE
粗略筛选的亚洲健康袜子

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#61]
袜4远比袜5节点多得多, 而且袜4里面才有真正的免费节点.
存活时间, 在线时间, 带宽都可靠得多.

玩不转袜4, 等于不会~~

粗略筛选的亚洲健康袜子
101.128.72.151:1080
101.255.17.137:1080
101.255.17.141:1080
101.255.17.142:1080
101.255.45.22:33555
101.78.209.84:1080
103.10.52.83:57290
103.10.52.83:64222
103.12.119.5:33115
103.12.161.1:1080
103.14.27.174:1080
103.16.112.1:1080
103.16.112.205:1080
103.16.112.221:1080
103.195.142.88:9999
103.206.247.178:34411
103.214.182.190:15444
103.214.182.213:15444
103.214.182.249:15444
103.214.55.6:1080
103.228.119.125:34411
103.23.135.145:34411
103.231.202.70:1080
103.247.217.124:22020
103.31.250.122:1080
103.43.202.18:1080
103.43.202.25:1080
103.53.0.178:1080
103.56.205.114:11080
103.69.218.48:33555
103.7.250.235:33555
103.86.0.6:33535
103.9.134.114:1080
110.5.111.214:1080
110.77.172.90:31431
110.77.177.254:34411
110.77.181.91:34411
110.77.200.181:34411
110.77.200.214:34411
110.77.200.98:34411
110.77.200.9:34411
110.77.201.159:34411
110.77.201.74:34411
110.77.207.53:34411
113.161.88.223:31431
113.190.244.106:33535
113.11.133.198:34411
111.119.210.10:1080
110.78.178.39:31431
110.78.155.150:34411
110.78.155.170:34411
110.78.137.213:34411
110.77.240.216:34411
110.77.219.45:34411
110.77.219.94:34411
110.77.226.50:34411
110.77.232.166:34411
110.77.213.87:34411
110.77.210.75:34411
114.134.186.25:1080
114.33.75.32:1080
114.69.240.214:33535
115.124.75.86:1080
115.166.128.230:1080
116.197.134.146:1080
116.212.137.235:32323
116.58.236.165:34411
116.58.240.156:31431
116.66.197.148:1080
117.4.136.11:18952
117.74.125.125:1080
117.74.125.238:1080
118.172.127.118:1080
118.193.21.70:1080
118.70.124.34:1080
119.40.97.146:31431
119.42.123.23:34411
123.49.53.194:33115
124.195.19.18:1080
124.41.240.63:33012
125.162.247.37:1080
125.21.255.50:33012
13.127.5.170:1080
139.192.181.168:1080
139.255.55.146:33555
14.139.188.34:1080
14.139.239.22:31431
150.107.141.94:1080
159.192.227.127:31431
172.104.67.19:28938
174.138.21.73:1999
175.100.5.64:33012
203.91.118.71:1080
203.77.230.116:1080
203.77.230.117:1080
203.77.230.114:1080
203.177.36.84:33555
203.189.135.107:1080
203.142.34.36:32323
203.153.113.226:31431
202.86.220.161:1080
202.59.140.76:33555
202.168.249.170:13058
202.179.4.70:33012
202.148.10.195:1080
202.141.246.166:1080
202.141.246.90:33012
180.246.62.1:1080
180.183.98.196:34411
180.148.215.101:1080
180.183.14.200:34411
211.108.3.235:8888
211.108.3.238:816
219.85.176.232:8080
220.143.161.233:3129
220.143.165.123:3129
220.143.172.104:3129
220.143.174.245:3129
220.143.174.60:3129
220.143.175.141:3129
223.196.89.183:34411
27.109.8.166:34411
36.255.135.128:33012
36.37.180.59:1080
36.66.218.153:1080
36.66.53.191:1080
36.67.24.255:33325
36.78.255.64:1080
36.80.112.26:1080
42.201.137.230:1080
43.231.22.140:1080
42.115.91.82:33012
43.239.73.81:1080
43.252.11.234:34411
43.252.159.195:11080
45.114.152.29:1080
45.119.112.16:34411
45.76.219.207:1080
47.52.70.195:1080
47.90.92.92:8090
52.76.200.171:1080
59.152.11.182:33555
59.152.5.6:33555
59.152.95.54:33555
61.6.130.64:1080
61.6.61.214:33535
61.6.71.5:33115
61.6.91.223:31231
61.7.131.141:34411
61.7.131.47:34411
61.7.131.56:34411
61.7.131.90:34411
61.8.75.186:1080
61.91.79.42:34411
88.204.214.122:1081
92.46.7.137:1080
92.62.72.242:1080
92.62.79.231:1080
96.9.90.124:33555
96.9.90.62:33555

**Comment by blob2015** [comment]
感谢J哥
