### ISSUE TITLE
○○○中立性软件更新信息

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#62]
洋葱 Tor 
https://dist.torproject.org/torbrowser/7.0.11/torbrowser-install-7.0.11_zh-CN.exe

**Comment by blob2015** [comment]
都到7了，又是一年了

**Comment by jasonliul** [comment]
WinSCP 5.11.3
https://sourceforge.net/projects/winscp/files/WinSCP/5.11.3/

Setup
https://sourceforge.net/projects/winscp/files/WinSCP/5.11.3/WinSCP-5.11.3-Setup.exe/download

Portable
https://sourceforge.net/projects/winscp/files/WinSCP/5.11.3/WinSCP-5.11.3-Portable.zip/download

v 5.11.3
    TLS/SSL core upgraded to OpenSSL 1.0.2n.
    Translations added: Korean; and updated: Bahasa Indonesia, Finnish and Spanish.
    Bug fix: Official extension Generate HTTP URL cannot copy multiple URLs to clipboard. 1567
    Bug fix: Parent directory icon broken on 250% scaling and higher. 1570
    Bug fix: Resizing of Synchronization checklist window does not stop when mouse button is released. 1571
    Bug fix: It was not possible to answer prompts with non-ascii answers in winscp.com. 1573
    Bug fix: Failure when starting with window position configuration, saved on lower DPI, that does not fit anymore on lower resolution caused by higher DPI. 1576
    Bug fix: Failure when changing remote working directory using directory tree. 1572
    Bug fix: XML log and .NET assembly API does not use an absolute path for source of SCP download.
    Bug fix: WinSCP .NET assembly hangs when the XML log cannot be parsed. 1582
    Bug fix: WinSCP .NET assembly cannot work with files containing control characters. 1583
    Bug fix: Failure when coping local custom command that works with remote files to clipboard.
    Bug fix: Failure when using Ctrl+Tab keyboard shortcut with no session opened. 1585
    Bug fix: When parsing MLSD listing, file name was incorrectly tried to be interpreted against various rare path syntaxes, leading to wrong name being displayed. 1587
