### ISSUE TITLE
有趣的中国墙国野史~

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#67]
https://blog.yandere.moe/moe/gfw-vs-proxy/97.html

**Comment by blob2015** [comment]
J哥，关于工具，搞个汇总帖吧（可以分几个）？然后再偶尔发些个这个，否则，霸屏，个人感觉有点点干扰到主任？

**Comment by blob2015** [comment]
或者定期关闭一批？——一个星期，或者一个月？
