### ISSUE TITLE
中东新玩具 破坏者Fshekan 0.94

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#82]
中东新玩具 破坏者Fshekan 0.92
http://fshekan.com/

下载
http://fshekan.com/download/Fshekan_exe/Fshekan.exe

The spoiler has the ability to modify IP and Local DNS and encrypt data that can be accessed through filtered sites. This filter is portable and does not require installation and can be used for free and without limitation.

Changes in this version:
    Bug fix in lower edits
    Optimize app display

The Simorgh site has been operating since 2009 to create proxy and free and secure VPNs. In the last two years, the group's activities focused on individuals and groups such as journalists of political, civil and dissident activists. Now the Simorgh Group of the site has decided to expand its scope and publicize its experience in overcoming filtering as well as security on the Internet.

One of the products of the Simorgh site is the site for filtering the "Fshekan" program. You can download this app for free and enjoy tens of fast-speed servers with unlimited security on the Internet.

**Comment by Kisesy** [comment]
这名字霸气哦

**Comment by jasonliul** [comment]
其实是绿凤凰组织的新玩具, 看起来还是用putty, 不过必须导入证书.

**Comment by blob2015** [comment]
J哥给我们各种最新的前线战报啊

**Comment by jasonliul** [comment]
Fshekan 0.93
遭到攻击, 他们重调了服务器~~

**Comment by jasonliul** [comment]
0.94
 	Changes
Fixed: failed to connect to servers at low speed

自带前置的测试者版本
 http://www.mediafire.com/file/jndded9a6ko9k5t/Fshekan_180107.zip
