### ISSUE TITLE
各位的Hash值对得起来不？

### ISSUE THREAD

**Issue by blob2015** [Kisesy/gscan_quic#87]
俺的gscan_quic_windows_386-v3.7是8f9e3ee846fef886a8439ea8c06aa841（MD5），但主任提供的是f426f4b002ce57ee5d9a233d6bfdde6a。
莫不是，又是俺下载不完整？

**Comment by Kisesy** [comment]
嗯...其实是我把 v3.7 写成 3.7 了，我改了以后就自动重编译了，但是 md5sum 因为重名所以就没自动上传
真正的 hash 到这里看吧，这个是错不了的
https://travis-ci.org/Kisesy/gscan_quic/builds/324037670

	$ md5sum *.7z *.xz *.bz2 | tee md5sum
	8f9e3ee846fef886a8439ea8c06aa841  gscan_quic_windows_386-v3.7.7z
	eb343d2c0ee1ed1181cdd386ac5c188a  gscan_quic_windows_amd64-v3.7.7z
	36ec280f7bbeadbab9d7a8b3dbe8edbf  gscan_quic_linux_386-v3.7.tar.xz
	feb8a2402f1f92f4a317abe0a8de33a8  gscan_quic_linux_amd64-v3.7.tar.xz
	2763cfb4d50b18a7c013dfd6e3db99d1  gscan_quic_darwin_amd64-v3.7.tar.bz2
	ca4fbb48eb32a076ab7629f70d74745a  gscan_quic_linux_arm-v3.7.tar.bz2

	0.06s$ sha1sum *.7z *.xz *.bz2 | tee sha1sum
	05e4691a0b6446a8631001f4b3390b586b880f6e  gscan_quic_windows_386-v3.7.7z
	50f50660ccf1bad34a36c4029087c0fc933a9f80  gscan_quic_windows_amd64-v3.7.7z
	35b66533dd1dfb3b187e38730c638ce29b963540  gscan_quic_linux_386-v3.7.tar.xz
	759cc8b38d66a422d6d5f91e8a3221e78e152755  gscan_quic_linux_amd64-v3.7.tar.xz
	78a834bd91424ac10c6b69223905afb0a65d58de  gscan_quic_darwin_amd64-v3.7.tar.bz2
	cc93f63bf2b864a4326789775e530d65e0c597f9  gscan_quic_linux_arm-v3.7.tar.bz2

**Comment by blob2015** [comment]
感谢主任解惑

**Comment by blob2015** [comment]
主任竟然会斟酌字句，改易“并发数”为“并发” :grinning:
