### ISSUE TITLE
反审查VPN --Tuxler

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#88]
[img]https://www.tuxler.com/wp-content/uploads/2016/03/tuxler-vpn-screenshot.png[/img]
Tuxler
https://www.tuxler.com/

Tuxler -Anti censorship tool, free VPN.

Free user:
Regular Speed, Unlimited Bandwidth, 70.000+ Fresh IPs Every Month 
Limited Location Changes,Limited Access to Locations
About 92 country, 250 hosts.

Разработчик: Tuxler Privacy Technologies, Inc.
Cтатус: Бесплатно
Язык: Английский, 

Tuxler 1.0
https://www.tuxler.com/download-mac-win-lin/

美国公司提供的反审查VPN, 不限流量, 中速, 约 92个国家, 250个节点

**Comment by blob2015** [comment]
感谢J哥
