### ISSUE TITLE
v3.8: 支持 Ping, 主任的瑞士军刀

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#89]
好罢, 搞不明白鸟~~
:)

**Comment by Kisesy** [comment]
其实就是批量 ping，当然很多工具都可以，就是顺便支持...

**Comment by Kisesy** [comment]
往后还会支持 SOCKS4/SOCKS4A/SOCKS5，当然，虽然简单，但是这里面有坑
因为又回到了内容验证上来了，如果简单判断这类IP，那么只要连接成功，并且 http 访问成功即可
但是无法对网站内容进行验证，也许这个IP http 成功之后，返回200状态码，但是网站内容却是 404 not found，这都是有可能的

**Comment by 2378** [comment]
mse 不报毒了 很好:stuck_out_tongue:

**Comment by Kisesy** [comment]
@2378 是32位下吗

**Comment by 2378** [comment]
v3.1之后就不报了
之前amd64也报

**Comment by tec1987** [comment]
更新好快，主任辛苦了

**Comment by jzmswe** [comment]
MSE报毒，我就换NOD 32 4.2.76.1了，因为MSE别的也经常报毒。换了NOD感觉好多了。

**Comment by 2378** [comment]
报毒这不是mse的锅 修复内存泄露之前 
很多avs都报
去VirusTotal一试就知道

**Comment by jzmswe** [comment]
@2378 不只是这个软件，别的一些软件MSE也报，就是说，MSE误杀率很高，NOD就很好，4.2.76.1同时也很小巧。

**Comment by 2378** [comment]
看个人喜好吧
“误杀”这玩意 一般人真没有发言权 
例如内存泄露 可以是软件bug 也可以是木马攻击造成 代码世界有时就是“一纸之隔”

**Comment by blob2015** [comment]
主任实在啊，有所更改、修复，也不换版本 :grinning:

**Comment by blob2015** [comment]
3.9 支持端口了
