### ISSUE TITLE
程序卡住了？？？。。。

### ISSUE THREAD

**Issue by tec1987** [Kisesy/gscan_quic#97]
先说一下配置情况
最新3.9版，
"ScanWorker": 8,
"ScanMode": "quic",
"QUIC": {
    "Level": 1,
其它没什么改动
”iprange_quic.txt“里是4500多行，每行一个IP（不是IP段）

如图：
![test](https://user-images.githubusercontent.com/23297763/34909143-8e8b6798-f8d6-11e7-99c0-bd7baee6bc3a.png)

**Comment by tec1987** [comment]
貌似不是线程问题，而是程序卡住不动了。。。
Ctrl+C也没反应。。。

**Comment by jasonliul** [comment]
这个比较奇怪, 通常4000左右ip运行良好.
也就是大约15个完整字段...

或者中间包含无效格式, 或者无效ip...

**Comment by kirbyzhu** [comment]
是不是鼠标点到cmd界面上了？

**Comment by tec1987** [comment]
@jasonliul 应该跟IP无关，同样IP再测一遍就没事
@kirbyzhu 绝对不是，Ctrl+C都不好使。。。

可能是系统问题，暂时无法复现，先不管了

**Comment by tec1987** [comment]
@Kisesy 又出现了几次。。。请主任有空看下，附件是相关截图和dump文件

IP列表是100个/24的IP段

[01.zip](https://github.com/Kisesy/gscan_quic/files/1629505/01.zip)
[02.zip](https://github.com/Kisesy/gscan_quic/files/1629509/02.zip)

完整的dump文件压缩后有6M，要的话明天上传

**Comment by Kisesy** [comment]
我也不好说，因为xp下还有不少问题，上次我修了一次内存泄漏，但是 sishentibu 反馈xp下还是有内存泄漏

或者这个问题跟我第一次改写gscan_quic时的卡住，是一个问题，因为我上次修内存泄漏就把这些用来解决卡住问题的代码都删掉了...

我试试改用go1.9编译，看看能不能解决..

**Comment by tec1987** [comment]
好的，感谢社长

今天在公司电脑上跑了两遍（也是XP），没出现问题。。。

**Comment by tec1987** [comment]
又卡死了。。。
看来XP真是不能用了

**Comment by Kisesy** [comment]
2.0 可能没问题
也不知道哪里的问题，同样的代码，3.x 就内存泄漏
也许哪一天，我更新一下quic-go就好了也说不定，唉，这些东西就是这么操蛋 :trollface:

**Comment by tec1987** [comment]
不知道是不是quic-go 的问题？
或者是Go逐渐退出对XP的支持了？

**Comment by Kisesy** [comment]
@tec1987 你试试 3.7 会不会卡住，它以后的版本我把互斥锁改成读写锁了，也可能是这问题

**Comment by tec1987** [comment]
@Kisesy
好的，我试一下

**Comment by tec1987** [comment]
。。。还是不行，照样卡住，附件是log，log也时有时无的

我再去试试最新编译的版本


[Err-180117.zip](https://github.com/Kisesy/gscan_quic/files/1639338/Err-180117.zip)

**Comment by Kisesy** [comment]
其实也不需要测了，这些毛病看起来就是内存泄漏引起的
如果tls或者sni扫起来没问题，那么也可以推断是quic-go的问题，或者quic-go不太兼容xp
在我这里 win7 32位下， lv3 等级下扫描四万多IP，内存是保持在11M上下的

![20171221144518](https://user-images.githubusercontent.com/5843694/35050200-360e28c6-fbdd-11e7-8d0e-5e0c579dec17.png)

等我以后更新quic-go试试，我现在不太敢更新，怕一更新又会有更多问题

**Comment by tec1987** [comment]
@Kisesy
好吧，实在不行就换系统用。。。

**Comment by Kisesy** [comment]
[gscan_quic.zip](https://github.com/Kisesy/gscan_quic/files/1642494/gscan_quic.zip)
@tec1987 我用最新版 quic-go 编译的，你试试看，证书部分我还没改，所以应该扫不到IP，你只看看扫IP的时候内存是不是一直上涨就行

**Comment by tec1987** [comment]
@Kisesy 新版quic-go编译的我正在测试，明天给你答复。

用4.0版的内存没有一直增长，但是仍然会卡住。。。
 4.0版卡住后任务管理器显示如图：
![default](https://user-images.githubusercontent.com/23297763/35110662-52d68142-fcb4-11e7-8c64-c2d238c353c5.png)

**Comment by Kisesy** [comment]
是吗，那就好，多谢测试，但是我已经忘记怎么修复证书返回了... :trollface:

**Comment by tec1987** [comment]
。。。先不要证书，只做QUIC支持和版本检测如何？

**Comment by Kisesy** [comment]
我已经改好了，等会你可以再试试看最新版

**Comment by tec1987** [comment]
嗯，辛苦了

**Comment by sishentibu** [comment]
lede下，用4.1扫描卡住了。。
上面有个版本是无问题的，貌似似是3.8.。。忘记了。。。

**Comment by Kisesy** [comment]
@sishentibu  4.1 版还有内存泄漏吗？

**Comment by Kisesy** [comment]
有几个关键版本: 3.7 4.0 4.1 4.2 4.3，这几个版本都各不相同，非常难测

**Comment by sishentibu** [comment]
@Kisesy 我那破机器装xp，aria2老出错，用不了，我又刷成lede x86的了
4.1我是用 nohup 重定向输出了的，看到有8小时不动了，我就强制结束了。正常情况下，过段时间就有个扫描完1000个的提示的。
相同配置，3.8就没有问题

**Comment by tec1987** [comment]
@sishentibu 3.8能用就不要折腾了，新版没多什么特性。。。

**Comment by sishentibu** [comment]
@tec1987 这不是看到有新版本忍不住要更新嘛。我2.0版本其实就够用了，只用扫扫gop的ip而以
