### ISSUE TITLE
v 4.3, 谷主任也来飚版本号~~

### ISSUE THREAD

**Issue by jasonliul** [Kisesy/gscan_quic#98]
快走去升级...
:)

**Comment by jasonliul** [comment]
4.3反倒中途卡死了....

**Comment by Kisesy** [comment]
厉害了，4.2 或者 4.1 卡不卡

**Comment by jasonliul** [comment]
4.2 版本正常, win7 x64下面39M内存, 没有问题

**Comment by jasonliul** [comment]
多试几次, 4.2偶尔也卡死...
之前的4.1没有出过问题

**Comment by Kisesy** [comment]
4.2 卡死，4.1 却不卡，有些奇怪，要是这样，我觉得之前的版本可能也卡 :trollface:  只是平常没注意

**Comment by jasonliul** [comment]
重启, 4.2依然卡死.
4.1 没有问题,傍晚我重新搜索了手头的IP段, 重复10几次,没有问题

**Comment by jasonliul** [comment]
如果要支持XP, 还不如用旧版GO编译, 或许反倒可以...

**Comment by tec1987** [comment]
XP 目前使用4.1 没发现什么问题

**Comment by jasonliul** [comment]
@tec1987
你不早说?
:)

**Comment by Kisesy** [comment]
行，有不卡的版本就好，我把新版删除了..

**Comment by tec1987** [comment]
@jasonliul
J哥，你是不是最近没关注issues，看 #97

**Comment by jasonliul** [comment]
@tec1987 最近四处捉雕去了~~

**Comment by whhxmwhh** [comment]
有你们的努力，给世界光明！
